/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Severity levels for DOCX comments.
 * @export
 */
export const CommentSeverity = {
  None: 'none',
  Low: 'low',
  Medium: 'medium',
  High: 'high',
} as const;
export type CommentSeverity = (typeof CommentSeverity)[keyof typeof CommentSeverity];

export function instanceOfCommentSeverity(value: any): boolean {
  for (const key in CommentSeverity) {
    if (Object.prototype.hasOwnProperty.call(CommentSeverity, key)) {
      if (CommentSeverity[key as keyof typeof CommentSeverity] === value) {
        return true;
      }
    }
  }
  return false;
}

export function CommentSeverityFromJSON(json: any): CommentSeverity {
  return CommentSeverityFromJSONTyped(json, false);
}

export function CommentSeverityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentSeverity {
  return json as CommentSeverity;
}

export function CommentSeverityToJSON(value?: CommentSeverity | null): any {
  return value as any;
}

export function CommentSeverityToJSONTyped(value: any, ignoreDiscriminator: boolean): CommentSeverity {
  return value as CommentSeverity;
}
