/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocxGenerationState } from './DocxGenerationState';
import {
  DocxGenerationStateFromJSON,
  DocxGenerationStateFromJSONTyped,
  DocxGenerationStateToJSON,
  DocxGenerationStateToJSONTyped,
} from './DocxGenerationState';
import type { WorkflowRun } from './WorkflowRun';
import {
  WorkflowRunFromJSON,
  WorkflowRunFromJSONTyped,
  WorkflowRunToJSON,
  WorkflowRunToJSONTyped,
} from './WorkflowRun';

/**
 *
 * @export
 * @interface DocxGenerationWorkflowDetail
 */
export interface DocxGenerationWorkflowDetail {
  /**
   *
   * @type {WorkflowRun}
   * @memberof DocxGenerationWorkflowDetail
   */
  run: WorkflowRun;
  /**
   *
   * @type {DocxGenerationState}
   * @memberof DocxGenerationWorkflowDetail
   */
  state: DocxGenerationState;
}

/**
 * Check if a given object implements the DocxGenerationWorkflowDetail interface.
 */
export function instanceOfDocxGenerationWorkflowDetail(value: object): value is DocxGenerationWorkflowDetail {
  if (!('run' in value) || value['run'] === undefined) return false;
  if (!('state' in value) || value['state'] === undefined) return false;
  return true;
}

export function DocxGenerationWorkflowDetailFromJSON(json: any): DocxGenerationWorkflowDetail {
  return DocxGenerationWorkflowDetailFromJSONTyped(json, false);
}

export function DocxGenerationWorkflowDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DocxGenerationWorkflowDetail {
  if (json == null) {
    return json;
  }
  return {
    run: WorkflowRunFromJSON(json['run']),
    state: DocxGenerationStateFromJSON(json['state']),
  };
}

export function DocxGenerationWorkflowDetailToJSON(json: any): DocxGenerationWorkflowDetail {
  return DocxGenerationWorkflowDetailToJSONTyped(json, false);
}

export function DocxGenerationWorkflowDetailToJSONTyped(
  value?: DocxGenerationWorkflowDetail | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    run: WorkflowRunToJSON(value['run']),
    state: DocxGenerationStateToJSON(value['state']),
  };
}
