/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocxGenerationWorkflowConfig } from './DocxGenerationWorkflowConfig';
import {
  DocxGenerationWorkflowConfigFromJSON,
  DocxGenerationWorkflowConfigFromJSONTyped,
  DocxGenerationWorkflowConfigToJSON,
  DocxGenerationWorkflowConfigToJSONTyped,
} from './DocxGenerationWorkflowConfig';
import type { DocxComment } from './DocxComment';
import {
  DocxCommentFromJSON,
  DocxCommentFromJSONTyped,
  DocxCommentToJSON,
  DocxCommentToJSONTyped,
} from './DocxComment';
import type { WorkflowError } from './WorkflowError';
import {
  WorkflowErrorFromJSON,
  WorkflowErrorFromJSONTyped,
  WorkflowErrorToJSON,
  WorkflowErrorToJSONTyped,
} from './WorkflowError';

/**
 * State for DOCX generation workflow.
 * @export
 * @interface DocxGenerationState
 */
export interface DocxGenerationState {
  /**
   * Errors that occurred during the workflow execution.
   * @type {Array<WorkflowError>}
   * @memberof DocxGenerationState
   */
  errors?: Array<WorkflowError>;
  /**
   *
   * @type {string}
   * @memberof DocxGenerationState
   */
  type?: DocxGenerationStateTypeEnum;
  /**
   *
   * @type {DocxGenerationWorkflowConfig}
   * @memberof DocxGenerationState
   */
  config: DocxGenerationWorkflowConfig;
  /**
   *
   * @type {Array<DocxComment>}
   * @memberof DocxGenerationState
   */
  comments?: Array<DocxComment> | null;
  /**
   *
   * @type {Array<any>}
   * @memberof DocxGenerationState
   */
  chunks?: Array<any> | null;
  /**
   *
   * @type {string}
   * @memberof DocxGenerationState
   */
  originalFilePath?: string | null;
  /**
   *
   * @type {string}
   * @memberof DocxGenerationState
   */
  baseFileName?: string | null;
  /**
   *
   * @type {string}
   * @memberof DocxGenerationState
   */
  generatedFilePath?: string | null;
  /**
   *
   * @type {string}
   * @memberof DocxGenerationState
   */
  filename?: string | null;
}

/**
 * @export
 */
export const DocxGenerationStateTypeEnum = {
  DocxGeneration: 'docx_generation',
} as const;
export type DocxGenerationStateTypeEnum =
  (typeof DocxGenerationStateTypeEnum)[keyof typeof DocxGenerationStateTypeEnum];

/**
 * Check if a given object implements the DocxGenerationState interface.
 */
export function instanceOfDocxGenerationState(value: object): value is DocxGenerationState {
  if (!('config' in value) || value['config'] === undefined) return false;
  return true;
}

export function DocxGenerationStateFromJSON(json: any): DocxGenerationState {
  return DocxGenerationStateFromJSONTyped(json, false);
}

export function DocxGenerationStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocxGenerationState {
  if (json == null) {
    return json;
  }
  return {
    errors: json['errors'] == null ? undefined : (json['errors'] as Array<any>).map(WorkflowErrorFromJSON),
    type: json['type'] == null ? undefined : json['type'],
    config: DocxGenerationWorkflowConfigFromJSON(json['config']),
    comments: json['comments'] == null ? undefined : (json['comments'] as Array<any>).map(DocxCommentFromJSON),
    chunks: json['chunks'] == null ? undefined : json['chunks'],
    originalFilePath: json['original_file_path'] == null ? undefined : json['original_file_path'],
    baseFileName: json['base_file_name'] == null ? undefined : json['base_file_name'],
    generatedFilePath: json['generated_file_path'] == null ? undefined : json['generated_file_path'],
    filename: json['filename'] == null ? undefined : json['filename'],
  };
}

export function DocxGenerationStateToJSON(json: any): DocxGenerationState {
  return DocxGenerationStateToJSONTyped(json, false);
}

export function DocxGenerationStateToJSONTyped(
  value?: DocxGenerationState | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    errors: value['errors'] == null ? undefined : (value['errors'] as Array<any>).map(WorkflowErrorToJSON),
    type: value['type'],
    config: DocxGenerationWorkflowConfigToJSON(value['config']),
    comments: value['comments'] == null ? undefined : (value['comments'] as Array<any>).map(DocxCommentToJSON),
    chunks: value['chunks'],
    original_file_path: value['originalFilePath'],
    base_file_name: value['baseFileName'],
    generated_file_path: value['generatedFilePath'],
    filename: value['filename'],
  };
}
