/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentSeverity } from './CommentSeverity';
import {
  CommentSeverityFromJSON,
  CommentSeverityFromJSONTyped,
  CommentSeverityToJSON,
  CommentSeverityToJSONTyped,
} from './CommentSeverity';

/**
 * Represents a comment to be added to a docx file.
 * @export
 * @interface DocxComment
 */
export interface DocxComment {
  /**
   *
   * @type {number}
   * @memberof DocxComment
   */
  chunkIndex: number;
  /**
   *
   * @type {string}
   * @memberof DocxComment
   */
  text: string;
  /**
   *
   * @type {string}
   * @memberof DocxComment
   */
  commentText: string;
  /**
   *
   * @type {CommentSeverity}
   * @memberof DocxComment
   */
  severity?: CommentSeverity | null;
  /**
   *
   * @type {string}
   * @memberof DocxComment
   */
  author?: string | null;
  /**
   *
   * @type {string}
   * @memberof DocxComment
   */
  shareLink?: string | null;
}

/**
 * Check if a given object implements the DocxComment interface.
 */
export function instanceOfDocxComment(value: object): value is DocxComment {
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('text' in value) || value['text'] === undefined) return false;
  if (!('commentText' in value) || value['commentText'] === undefined) return false;
  return true;
}

export function DocxCommentFromJSON(json: any): DocxComment {
  return DocxCommentFromJSONTyped(json, false);
}

export function DocxCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocxComment {
  if (json == null) {
    return json;
  }
  return {
    chunkIndex: json['chunk_index'],
    text: json['text'],
    commentText: json['comment_text'],
    severity: json['severity'] == null ? undefined : CommentSeverityFromJSON(json['severity']),
    author: json['author'] == null ? undefined : json['author'],
    shareLink: json['share_link'] == null ? undefined : json['share_link'],
  };
}

export function DocxCommentToJSON(json: any): DocxComment {
  return DocxCommentToJSONTyped(json, false);
}

export function DocxCommentToJSONTyped(value?: DocxComment | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    chunk_index: value['chunkIndex'],
    text: value['text'],
    comment_text: value['commentText'],
    severity: CommentSeverityToJSON(value['severity']),
    author: value['author'],
    share_link: value['shareLink'],
  };
}
