/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Config for DOCX generation workflow.
 * @export
 * @interface DocxGenerationWorkflowConfig
 */
export interface DocxGenerationWorkflowConfig {
  /**
   *
   * @type {string}
   * @memberof DocxGenerationWorkflowConfig
   */
  projectId?: string | null;
  /**
   *
   * @type {string}
   * @memberof DocxGenerationWorkflowConfig
   */
  openaiApiKey?: string | null;
  /**
   *
   * @type {string}
   * @memberof DocxGenerationWorkflowConfig
   */
  type?: DocxGenerationWorkflowConfigTypeEnum;
  /**
   * Workflow run ID of the claim substantiation run to generate DOCX from
   * @type {string}
   * @memberof DocxGenerationWorkflowConfig
   */
  claimSubstantiationRunId: string;
  /**
   *
   * @type {string}
   * @memberof DocxGenerationWorkflowConfig
   */
  shareToken?: string | null;
}

/**
 * @export
 */
export const DocxGenerationWorkflowConfigTypeEnum = {
  DocxGeneration: 'docx_generation',
} as const;
export type DocxGenerationWorkflowConfigTypeEnum =
  (typeof DocxGenerationWorkflowConfigTypeEnum)[keyof typeof DocxGenerationWorkflowConfigTypeEnum];

/**
 * Check if a given object implements the DocxGenerationWorkflowConfig interface.
 */
export function instanceOfDocxGenerationWorkflowConfig(value: object): value is DocxGenerationWorkflowConfig {
  if (!('claimSubstantiationRunId' in value) || value['claimSubstantiationRunId'] === undefined) return false;
  return true;
}

export function DocxGenerationWorkflowConfigFromJSON(json: any): DocxGenerationWorkflowConfig {
  return DocxGenerationWorkflowConfigFromJSONTyped(json, false);
}

export function DocxGenerationWorkflowConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DocxGenerationWorkflowConfig {
  if (json == null) {
    return json;
  }
  return {
    projectId: json['project_id'] == null ? undefined : json['project_id'],
    openaiApiKey: json['openai_api_key'] == null ? undefined : json['openai_api_key'],
    type: json['type'] == null ? undefined : json['type'],
    claimSubstantiationRunId: json['claim_substantiation_run_id'],
    shareToken: json['share_token'] == null ? undefined : json['share_token'],
  };
}

export function DocxGenerationWorkflowConfigToJSON(json: any): DocxGenerationWorkflowConfig {
  return DocxGenerationWorkflowConfigToJSONTyped(json, false);
}

export function DocxGenerationWorkflowConfigToJSONTyped(
  value?: DocxGenerationWorkflowConfig | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project_id: value['projectId'],
    openai_api_key: value['openaiApiKey'],
    type: value['type'],
    claim_substantiation_run_id: value['claimSubstantiationRunId'],
    share_token: value['shareToken'],
  };
}
