"""add_workflow_progress_table

Revision ID: 01a7c2a05b7d
Revises: 9dc9ecffd511
Create Date: 2026-01-08 17:00:25.854699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "01a7c2a05b7d"
down_revision: Union[str, None] = "9dc9ecffd511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_steps", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Single-column index for workflow_run_id lookups
    op.create_index(
        op.f("ix_workflow_progress_workflow_run_id"),
        "workflow_progress",
        ["workflow_run_id"],
        unique=False,
    )
    # Composite index for the common query pattern:
    # WHERE workflow_run_id = ? ORDER BY created_at
    op.create_index(
        "ix_workflow_progress_run_id_created_at",
        "workflow_progress",
        ["workflow_run_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_progress_run_id_created_at", table_name="workflow_progress")
    op.drop_index(
        op.f("ix_workflow_progress_workflow_run_id"), table_name="workflow_progress"
    )
    op.drop_table("workflow_progress")
    # ### end Alembic commands ###
