"""add rendered text to issue_edits

Revision ID: 1973e3ebac83
Revises: 98cb6b0f1548
Create Date: 2026-09-22 10:44:53.439546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1973e3ebac83'
down_revision: Union[str, None] = '98cb6b0f1548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Every existing row predates the rendered columns, and there is no way to
    # fill them in afterwards: the rendered form is worked out from the
    # markdown line the edit was quoted from, which the row does not carry.
    # Proposed edits are not live yet -- nothing reads these rows in
    # production -- so the rows go rather than the columns arriving nullable
    # and the export learning to cope with a half-filled one.
    op.execute("DELETE FROM issue_edits")
    op.add_column('issue_edits', sa.Column('display_text', sa.Text(), nullable=False))
    op.add_column('issue_edits', sa.Column('display_occurrence', sa.Integer(), nullable=False))
    op.add_column('issue_edits', sa.Column('display_replacement', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_edits', 'display_replacement')
    op.drop_column('issue_edits', 'display_occurrence')
    op.drop_column('issue_edits', 'display_text')
    # ### end Alembic commands ###
