"""add_feedback_visibility_to_projects

Revision ID: 1cc768ae2623
Revises: 638a72046e37
Create Date: 2026-03-17 17:22:26.233764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1cc768ae2623'
down_revision: Union[str, None] = '638a72046e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRIVATE', 'ISSUE_ONLY', 'FULL_PROJECT', name='feedbackvisibility').create(op.get_bind())
    op.add_column('projects', sa.Column('feedback_visibility', sa.Enum('PRIVATE', 'ISSUE_ONLY', 'FULL_PROJECT', name='feedbackvisibility'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'feedback_visibility')
    sa.Enum('PRIVATE', 'ISSUE_ONLY', 'FULL_PROJECT', name='feedbackvisibility').drop(op.get_bind())
    # ### end Alembic commands ###
