"""add start_line/end_line to issues

Revision ID: 1d6c512c344f
Revises: 3b1c8a9d2f04
Create Date: 2026-04-21 17:23:17.354495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d6c512c344f'
down_revision: Union[str, None] = '3b1c8a9d2f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('start_line', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('end_line', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'end_line')
    op.drop_column('issues', 'start_line')
    # ### end Alembic commands ###
