"""drop chat_messages, conversation moves to the checkpointer

Revision ID: 284108200780
Revises: a3c9e1f5b7d2
Create Date: 2026-09-07 18:23:35.833394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '284108200780'
down_revision: Union[str, None] = 'a3c9e1f5b7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing threads point at conversations that were never checkpointed, so
    # they would open empty. Every row so far is test data; start clean.
    op.execute("DELETE FROM chat_threads")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_thread_created'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_thread_message'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('chat_messages_thread_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('ix_chat_messages_thread_message'), 'chat_messages', ['thread_id', 'message_id'], unique=True)
    op.create_index(op.f('ix_chat_messages_thread_created'), 'chat_messages', ['thread_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
