"""remove chunk_index from issues

Revision ID: 37ed5633d338
Revises: 472f945f19b5
Create Date: 2026-02-16 14:16:49.891318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37ed5633d338'
down_revision: Union[str, None] = '472f945f19b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'chunk_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
