"""add show_experimental_features to users

Revision ID: 3f207b45e735
Revises: f6c0d2582e72
Create Date: 2026-01-30 15:38:31.102957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3f207b45e735"
down_revision: Union[str, None] = "f6c0d2582e72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "show_experimental_features",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "show_experimental_features")
    # ### end Alembic commands ###
