"""add_resolved_by_to_issues

Revision ID: 472f945f19b5
Revises: bc0838c50bec
Create Date: 2026-02-11 11:50:09.558770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '472f945f19b5'
down_revision: Union[str, None] = 'bc0838c50bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='issuestatus',
        new_values=['ACTIVE', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='issues', column_name='status')],
        enum_values_to_rename=[],
    )
    op.add_column('issues', sa.Column('resolved_by', sa.UUID(), nullable=True))
    op.add_column('issues', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'resolved_at')
    op.drop_column('issues', 'resolved_by')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='issuestatus',
        new_values=['ACTIVE', 'ARCHIVED', 'RESOLVED'],
        affected_columns=[TableReference(table_schema='public', table_name='issues', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
