"""Add role column to users table

Revision ID: 6c803193cd23
Revises: 01a7c2a05b7d
Create Date: 2026-01-14 13:56:48.330768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c803193cd23'
down_revision: Union[str, None] = '01a7c2a05b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'ADMIN', name='userrole').create(op.get_bind())
    op.add_column('users', sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='userrole', create_type=False), server_default='USER', nullable=False))
    op.drop_index(op.f('ix_workflow_progress_run_id_created_at'), table_name='workflow_progress')
    op.create_index(op.f('ix_workflow_progress_created_at'), 'workflow_progress', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_progress_created_at'), table_name='workflow_progress')
    op.create_index(op.f('ix_workflow_progress_run_id_created_at'), 'workflow_progress', ['workflow_run_id', 'created_at'], unique=False)
    op.drop_column('users', 'role')
    sa.Enum('USER', 'ADMIN', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
