"""add_gin_indexes

Revision ID: 73cd1358c54c
Revises: b3d7e9f12a45
Create Date: 2026-03-23 12:54:47.214006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73cd1358c54c'
down_revision: Union[str, None] = 'b3d7e9f12a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_feedback_feedback_text_trgm', 'feedback', ['feedback_text'], unique=False, postgresql_using='gin', postgresql_ops={'feedback_text': 'gin_trgm_ops'})
    op.create_index('ix_issues_description_trgm', 'issues', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_issues_long_description_trgm', 'issues', ['long_description'], unique=False, postgresql_using='gin', postgresql_ops={'long_description': 'gin_trgm_ops'})
    op.create_index('ix_issues_title_trgm', 'issues', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_projects_title_trgm', 'projects', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_users_email_trgm', 'users', ['email'], unique=False, postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    op.create_index('ix_users_name_trgm', 'users', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_name_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_users_email_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    op.drop_index('ix_projects_title_trgm', table_name='projects', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_issues_title_trgm', table_name='issues', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_issues_long_description_trgm', table_name='issues', postgresql_using='gin', postgresql_ops={'long_description': 'gin_trgm_ops'})
    op.drop_index('ix_issues_description_trgm', table_name='issues', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('ix_feedback_feedback_text_trgm', table_name='feedback', postgresql_using='gin', postgresql_ops={'feedback_text': 'gin_trgm_ops'})
    # ### end Alembic commands ###
