"""add microsoft word handoffs

Revision ID: 7a8e44e902a7
Revises: 821bcbafd48b
Create Date: 2026-10-09 09:45:24.925786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a8e44e902a7'
down_revision: Union[str, None] = '821bcbafd48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microsoft_word_handoffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requested_by_oid', sa.String(), nullable=False),
    sa.Column('requested_by_tid', sa.String(), nullable=True),
    sa.Column('requested_by_upn', sa.String(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=False),
    sa.Column('document_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microsoft_word_handoffs_created_at'), 'microsoft_word_handoffs', ['created_at'], unique=False)
    op.create_index(op.f('ix_microsoft_word_handoffs_requested_by_oid'), 'microsoft_word_handoffs', ['requested_by_oid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_microsoft_word_handoffs_requested_by_oid'), table_name='microsoft_word_handoffs')
    op.drop_index(op.f('ix_microsoft_word_handoffs_created_at'), table_name='microsoft_word_handoffs')
    op.drop_table('microsoft_word_handoffs')
    # ### end Alembic commands ###
