"""add annotation tables

Revision ID: 821bcbafd48b
Revises: 8df84d01ee8b
Create Date: 2026-09-28 17:36:08.354739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '821bcbafd48b'
down_revision: Union[str, None] = '8df84d01ee8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'RETIRED', name='annotationitemstatus').create(op.get_bind())
    sa.Enum('EXPECTED_ISSUE', 'DECOY', name='annotationitemkind').create(op.get_bind())
    op.create_table('annotation_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('annotation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('kind', postgresql.ENUM('EXPECTED_ISSUE', 'DECOY', name='annotationitemkind', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'RETIRED', name='annotationitemstatus', create_type=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['annotation_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'source_key', name='uq_annotation_items_set_source')
    )
    op.create_index(op.f('ix_annotation_items_set_id'), 'annotation_items', ['set_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['annotation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='uq_annotations_item_user')
    )
    op.create_index(op.f('ix_annotations_item_id'), 'annotations', ['item_id'], unique=False)
    op.create_index(op.f('ix_annotations_user_id'), 'annotations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_user_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_item_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_annotation_items_set_id'), table_name='annotation_items')
    op.drop_table('annotation_items')
    op.drop_table('annotation_sets')
    sa.Enum('EXPECTED_ISSUE', 'DECOY', name='annotationitemkind').drop(op.get_bind())
    sa.Enum('ACTIVE', 'RETIRED', name='annotationitemstatus').drop(op.get_bind())
    # ### end Alembic commands ###
