"""add_started_and_completed_dates_to_workflow_ru

Revision ID: 8b28e2a42549
Revises: 8fed267f38a8
Create Date: 2026-03-30 15:12:11.553352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b28e2a42549'
down_revision: Union[str, None] = '8fed267f38a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_runs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'completed_at')
    op.drop_column('workflow_runs', 'started_at')
    # ### end Alembic commands ###
