"""add model to workflow_runs

Revision ID: 8df84d01ee8b
Revises: 1973e3ebac83
Create Date: 2026-09-28 13:04:18.360442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8df84d01ee8b'
down_revision: Union[str, None] = '1973e3ebac83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'model')
    # ### end Alembic commands ###
