"""add rate_limiter_buckets

Revision ID: 8ece42fd6856
Revises: a03f3524ea71
Create Date: 2026-04-13 10:31:30.973227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ece42fd6856'
down_revision: Union[str, None] = 'a03f3524ea71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limiter_buckets',
    sa.Column('bucket_key', sa.String(), nullable=False),
    sa.Column('available_tokens', sa.Float(), nullable=False),
    sa.Column('last_refill_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bucket_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limiter_buckets')
    # ### end Alembic commands ###
