"""add_cancelled_status_to_workflow

Revision ID: 8fed267f38a8
Revises: 73cd1358c54c
Create Date: 2026-03-27 10:08:34.393665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '8fed267f38a8'
down_revision: Union[str, None] = '73cd1358c54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workflowrunstatus',
        new_values=['PENDING', 'RUNNING', 'COMPLETED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='workflow_runs', column_name='status', existing_server_default="'COMPLETED'::workflowrunstatus")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workflowrunstatus',
        new_values=['PENDING', 'RUNNING', 'COMPLETED'],
        affected_columns=[TableReference(table_schema='public', table_name='workflow_runs', column_name='status', existing_server_default="'COMPLETED'::workflowrunstatus")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
