"""add_config_options_to_project_model

Revision ID: 9dc9ecffd511
Revises: 4da476c9a29e
Create Date: 2025-12-24 13:49:35.095903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9dc9ecffd511'
down_revision: Union[str, None] = '4da476c9a29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('publication_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('target_audience', sa.String(), nullable=True))
    op.drop_index(op.f('ix_share_links_resource'), table_name='share_links')
    op.create_index(op.f('ix_share_links_resource_id'), 'share_links', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_resource_id'), table_name='share_links')
    op.create_index(op.f('ix_share_links_resource'), 'share_links', ['resource_type', 'resource_id'], unique=False)
    op.drop_column('projects', 'target_audience')
    op.drop_column('projects', 'domain')
    op.drop_column('projects', 'publication_date')
    # ### end Alembic commands ###
