"""add revision columns

Revision ID: a03f3524ea71
Revises: ddaeb39ae83a
Create Date: 2026-04-09 16:54:56.948481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a03f3524ea71'
down_revision: Union[str, None] = 'ddaeb39ae83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add columns as nullable first so existing rows aren't rejected
    op.add_column('files', sa.Column('revision', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('revision', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('current_revision', sa.Integer(), nullable=True))
    op.add_column('workflow_runs', sa.Column('revision', sa.Integer(), nullable=True))

    # 2. Backfill existing data
    # MAIN files get revision=1; SUPPORT/SUPPORTING_CANDIDATE stay NULL (shared across revisions)
    op.execute("UPDATE files SET revision = 1 WHERE role = 'main'")
    op.execute("UPDATE issues SET revision = 1")
    op.execute("UPDATE projects SET current_revision = 1")
    op.execute("UPDATE workflow_runs SET revision = 1")

    # 3. Make NOT NULL columns non-nullable now that data is backfilled
    op.alter_column('issues', 'revision', nullable=False)
    op.alter_column('projects', 'current_revision', nullable=False)
    op.alter_column('workflow_runs', 'revision', nullable=False)

    # 4. Create indexes
    op.create_index(op.f('ix_files_revision'), 'files', ['revision'], unique=False)
    op.create_index('ix_issues_project_revision', 'issues', ['project_id', 'revision'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'revision')
    op.drop_column('projects', 'current_revision')
    op.drop_index('ix_issues_project_revision', table_name='issues')
    op.drop_column('issues', 'revision')
    op.drop_index(op.f('ix_files_revision'), table_name='files')
    op.drop_column('files', 'revision')
    # ### end Alembic commands ###
