"""Add started_at and completed_at to workflow_runs

Revision ID: a1012c54e54a
Revises: 9dc9ecffd511
Create Date: 2026-01-13 16:23:59.097619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1012c54e54a'
down_revision: Union[str, None] = '9dc9ecffd511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_runs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'completed_at')
    op.drop_column('workflow_runs', 'started_at')
    # ### end Alembic commands ###
