"""Add unique contraint to user email

Revision ID: aef5202a5521
Revises: 6c803193cd23
Create Date: 2026-01-14 15:16:14.744230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "aef5202a5521"
down_revision: Union[str, None] = "6c803193cd23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_email", "users", type_="unique")
    # ### end Alembic commands ###
