"""add_issues_table_and_feedback_issue_fk

Revision ID: bc0838c50bec
Revises: 88eae8d7e7a6
Create Date: 2026-02-10 17:54:54.362389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc0838c50bec"
down_revision: Union[str, None] = "88eae8d7e7a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("langgraph_checkpoint_id", sa.String(length=255), nullable=True),
        sa.Column("issue_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("long_description", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("NONE", "LOW", "MEDIUM", "HIGH", name="severityenum"),
            nullable=False,
        ),
        sa.Column("workflow_type", sa.String(length=100), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column("chunk_indices", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", "RESOLVED", name="issuestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_issues_issue_hash"), "issues", ["issue_hash"], unique=False
    )
    op.create_index(
        op.f("ix_issues_project_id"), "issues", ["project_id"], unique=False
    )
    op.create_index(
        "ix_issues_project_status", "issues", ["project_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_issues_workflow_run_id"), "issues", ["workflow_run_id"], unique=False
    )
    op.create_index(
        "ix_issues_workflow_type",
        "issues",
        ["project_id", "workflow_type"],
        unique=False,
    )
    op.add_column("feedback", sa.Column("issue_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_feedback_issue_id"), "feedback", ["issue_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "feedback",
        "issues",
        ["issue_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feedback", type_="foreignkey")
    op.drop_index(op.f("ix_feedback_issue_id"), table_name="feedback")
    op.drop_column("feedback", "issue_id")
    op.drop_index("ix_issues_workflow_type", table_name="issues")
    op.drop_index(op.f("ix_issues_workflow_run_id"), table_name="issues")
    op.drop_index("ix_issues_project_status", table_name="issues")
    op.drop_index(op.f("ix_issues_project_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_issue_hash"), table_name="issues")
    op.drop_table("issues")
    # ### end Alembic commands ###
