"""add_file_artifact_columns

Revision ID: cbd53440b56f
Revises: aef5202a5521
Create Date: 2026-01-19 18:09:46.526257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cbd53440b56f"
down_revision: Union[str, None] = "aef5202a5521"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("markdown", sa.Text(), nullable=True))
    op.add_column(
        "files",
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "summary")
    op.drop_column("files", "markdown")
    # ### end Alembic commands ###
