"""add encrypted_openai_api_key to users

Revision ID: ddaeb39ae83a
Revises: 8b28e2a42549
Create Date: 2026-04-03 09:56:50.662498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ddaeb39ae83a'
down_revision: Union[str, None] = '8b28e2a42549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_openai_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_openai_api_key')
    # ### end Alembic commands ###
