"""add suggested_action to issues

Revision ID: f4ef6e0d9708
Revises: 1d6c512c344f
Create Date: 2026-04-28 17:23:34.132767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4ef6e0d9708'
down_revision: Union[str, None] = '1d6c512c344f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('suggested_action', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'suggested_action')
    # ### end Alembic commands ###
