"""add_index_to_workflow_run_project_id

Revision ID: f6c0d2582e72
Revises: cbd53440b56f
Create Date: 2026-01-22 19:31:23.309901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6c0d2582e72'
down_revision: Union[str, None] = 'cbd53440b56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workflow_runs_project_id'), 'workflow_runs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_runs_project_id'), table_name='workflow_runs')
    # ### end Alembic commands ###
