"""add project_id index to files table

Revision ID: f8b78f9b409e
Revises: 47e2d7642ba2
Create Date: 2025-12-09 11:52:06.161186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8b78f9b409e'
down_revision: Union[str, None] = '47e2d7642ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    # ### end Alembic commands ###
