from typing import List, Type

from langgraph.graph import StateGraph

from lib.workflows.citation_detection.graph import build_citation_detection_graph
from lib.workflows.citation_detection.state import (
    CitationDetectionConfig,
    CitationDetectionState,
)
from lib.workflows.document_processing.state import DocumentProcessingState
from lib.workflows.manifest import WorkflowManifest
from lib.workflows.models import DocumentIssue, WorkflowRunType
from lib.workflows.reference_extraction.state import ReferenceExtractionState
from lib.workflows.types import WorkflowState
from lib.workflows.util import get_state_by_type_or_raise


class CitationDetectionManifest(
    WorkflowManifest[CitationDetectionState, CitationDetectionConfig]
):
    type = WorkflowRunType.CITATION_DETECTION
    name = "Citation Detection"
    description = "Detect citations in document chunks"
    needs_web_search = False
    is_internal = False
    can_be_triggered_by_user = True
    required_dependencies = [
        WorkflowRunType.REFERENCE_EXTRACTION,
    ]

    def get_state_type(self) -> Type[CitationDetectionState]:
        """Get the type of the workflow state."""
        return CitationDetectionState

    def get_config_type(self) -> Type[CitationDetectionConfig]:
        """Get the type of the workflow config."""
        return CitationDetectionConfig

    def build_graph(self) -> StateGraph:
        """Build and return the graph of the workflow."""
        return build_citation_detection_graph()

    async def create_initial_state(
        self,
        config: CitationDetectionConfig,
        existing_states: List[WorkflowState],
    ) -> CitationDetectionState:
        """Create and return the initial state of the workflow."""

        # Get document processing artifacts from dependency workflow
        doc_processing_state: DocumentProcessingState = get_state_by_type_or_raise(
            WorkflowRunType.DOCUMENT_PROCESSING, existing_states
        )

        # Get extracted references from reference extraction workflow
        ref_extraction_state: ReferenceExtractionState = get_state_by_type_or_raise(
            WorkflowRunType.REFERENCE_EXTRACTION, existing_states
        )

        return CitationDetectionState(
            file=doc_processing_state.file,
            references=ref_extraction_state.references,
            chunks=doc_processing_state.chunks,
            config=config,
        )

    def convert_state_to_issues(
        self, state: CitationDetectionState, other_states: List[WorkflowState]
    ) -> List[DocumentIssue]:
        """Convert CitationDetectionState to issues."""

        # No issues generated by this workflow
        return []
