from typing import List, Type

from langgraph.graph import StateGraph

from lib.workflows.citation_detection.graph import build_citation_detection_graph
from lib.workflows.citation_detection.state import (
    CitationDetectionConfig,
    CitationDetectionState,
)
from lib.workflows.manifest import WorkflowManifest
from lib.workflows.models import DocumentIssue, WorkflowRunType
from lib.workflows.types import WorkflowState
from lib.workflows.util import get_main_file_id


class CitationDetectionManifest(
    WorkflowManifest[CitationDetectionState, CitationDetectionConfig]
):
    type = WorkflowRunType.CITATION_DETECTION
    name = "Citation Detection"
    description = "Detect citations in document chunks"
    needs_web_search = False
    is_internal = True
    required_dependencies = [
        WorkflowRunType.CHUNK_SPLITTING,
        WorkflowRunType.REFERENCE_EXTRACTION,
        WorkflowRunType.FOOTNOTE_EXTRACTION,
    ]

    def get_state_type(self) -> Type[CitationDetectionState]:
        """Get the type of the workflow state."""
        return CitationDetectionState

    def get_config_type(self) -> Type[CitationDetectionConfig]:
        """Get the type of the workflow config."""
        return CitationDetectionConfig

    def build_graph(self) -> StateGraph:
        """Build and return the graph of the workflow."""
        return build_citation_detection_graph()

    async def create_initial_state(
        self,
        config: CitationDetectionConfig,
        existing_states: List[WorkflowState],
    ) -> CitationDetectionState:
        """Create and return the initial state of the workflow."""

        return CitationDetectionState(
            type=WorkflowRunType.CITATION_DETECTION,
            file_id=get_main_file_id(existing_states),
            config=config,
        )

    def convert_state_to_issues(
        self, state: CitationDetectionState, other_states: List[WorkflowState]
    ) -> List[DocumentIssue]:
        """Convert CitationDetectionState to issues."""

        # No issues generated by this workflow
        return []
