// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AppendMessageApiChatThreadsThreadIdMessagesPostData,
  AppendMessageApiChatThreadsThreadIdMessagesPostErrors,
  AppendMessageApiChatThreadsThreadIdMessagesPostResponses,
  ApproveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePostData,
  ApproveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePostErrors,
  ApproveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePostResponses,
  BotMessagesApiMicrosoftTeamsMessagesPostData,
  BotMessagesApiMicrosoftTeamsMessagesPostErrors,
  BotMessagesApiMicrosoftTeamsMessagesPostResponses,
  CancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPostData,
  CancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPostErrors,
  CancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPostResponses,
  CheckPreflightApiPreflightPostData,
  CheckPreflightApiPreflightPostErrors,
  CheckPreflightApiPreflightPostResponses,
  CoreHeadRouteTusUuidHeadData,
  CoreHeadRouteTusUuidHeadErrors,
  CoreHeadRouteTusUuidHeadResponses,
  CoreOptionsRouteTusOptionsData,
  CoreOptionsRouteTusOptionsErrors,
  CoreOptionsRouteTusOptionsResponses,
  CorePatchRouteTusUuidPatchData,
  CorePatchRouteTusUuidPatchErrors,
  CorePatchRouteTusUuidPatchResponses,
  CreateProjectEndpointApiProjectsPostData,
  CreateProjectEndpointApiProjectsPostErrors,
  CreateProjectEndpointApiProjectsPostResponses,
  CreateRevisionEndpointApiProjectProjectIdRevisionsPostData,
  CreateRevisionEndpointApiProjectProjectIdRevisionsPostErrors,
  CreateRevisionEndpointApiProjectProjectIdRevisionsPostResponses,
  CreateThreadApiChatThreadsPostData,
  CreateThreadApiChatThreadsPostErrors,
  CreateThreadApiChatThreadsPostResponses,
  DeleteFeedbackApiFeedbackFeedbackIdDeleteData,
  DeleteFeedbackApiFeedbackFeedbackIdDeleteErrors,
  DeleteFeedbackApiFeedbackFeedbackIdDeleteResponses,
  DeleteProjectEndpointApiProjectProjectIdDeleteData,
  DeleteProjectEndpointApiProjectProjectIdDeleteErrors,
  DeleteProjectEndpointApiProjectProjectIdDeleteResponses,
  DeleteProjectFileEndpointApiProjectProjectIdFilesFileIdDeleteData,
  DeleteProjectFileEndpointApiProjectProjectIdFilesFileIdDeleteErrors,
  DeleteProjectFileEndpointApiProjectProjectIdFilesFileIdDeleteResponses,
  DeleteThreadApiChatThreadsThreadIdDeleteData,
  DeleteThreadApiChatThreadsThreadIdDeleteErrors,
  DeleteThreadApiChatThreadsThreadIdDeleteResponses,
  DisableProjectSharingApiProjectsProjectIdShareDisablePostData,
  DisableProjectSharingApiProjectsProjectIdShareDisablePostErrors,
  DisableProjectSharingApiProjectsProjectIdShareDisablePostResponses,
  DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetData,
  DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetErrors,
  DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetResponses,
  DownloadFileApiFilesDownloadFileIdGetData,
  DownloadFileApiFilesDownloadFileIdGetErrors,
  DownloadFileApiFilesDownloadFileIdGetResponses,
  DownloadLogApiAdminLogsDownloadFilenameGetData,
  DownloadLogApiAdminLogsDownloadFilenameGetErrors,
  DownloadLogApiAdminLogsDownloadFilenameGetResponses,
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetData,
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetErrors,
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetResponses,
  EnableProjectSharingApiProjectsProjectIdShareEnablePostData,
  EnableProjectSharingApiProjectsProjectIdShareEnablePostErrors,
  EnableProjectSharingApiProjectsProjectIdShareEnablePostResponses,
  ExportAdminFeedbacksCsvApiAdminFeedbacksExportGetData,
  ExportAdminFeedbacksCsvApiAdminFeedbacksExportGetErrors,
  ExportAdminFeedbacksCsvApiAdminFeedbacksExportGetResponses,
  ExtensionCreationRouteTusPost2Data,
  ExtensionCreationRouteTusPost2Errors,
  ExtensionCreationRouteTusPost2Responses,
  ExtensionCreationRouteTusPostData,
  ExtensionCreationRouteTusPostErrors,
  ExtensionCreationRouteTusPostResponses,
  ExtensionTerminationRouteTusUuidDeleteData,
  ExtensionTerminationRouteTusUuidDeleteErrors,
  ExtensionTerminationRouteTusUuidDeleteResponses,
  GetAboutContentApiAboutGetData,
  GetAboutContentApiAboutGetResponses,
  GetAdminFeedbacksApiAdminFeedbacksGetData,
  GetAdminFeedbacksApiAdminFeedbacksGetErrors,
  GetAdminFeedbacksApiAdminFeedbacksGetResponses,
  GetAppConfigApiAppConfigsKeyGetData,
  GetAppConfigApiAppConfigsKeyGetErrors,
  GetAppConfigApiAppConfigsKeyGetResponses,
  GetCurrentUserInfoApiUsersMeGetData,
  GetCurrentUserInfoApiUsersMeGetResponses,
  GetDashboardApiAdminDashboardGetData,
  GetDashboardApiAdminDashboardGetErrors,
  GetDashboardApiAdminDashboardGetResponses,
  GetDurationEstimatesApiWorkflowTypesDurationEstimatesGetData,
  GetDurationEstimatesApiWorkflowTypesDurationEstimatesGetErrors,
  GetDurationEstimatesApiWorkflowTypesDurationEstimatesGetResponses,
  GetFeedbackApiFeedbackGetData,
  GetFeedbackApiFeedbackGetErrors,
  GetFeedbackApiFeedbackGetResponses,
  GetIssueEndpointApiIssuesIssueIdGetData,
  GetIssueEndpointApiIssuesIssueIdGetErrors,
  GetIssueEndpointApiIssuesIssueIdGetResponses,
  GetProjectEndpointApiProjectProjectIdGetData,
  GetProjectEndpointApiProjectProjectIdGetErrors,
  GetProjectEndpointApiProjectProjectIdGetResponses,
  GetProjectFeedbackApiFeedbackProjectProjectIdGetData,
  GetProjectFeedbackApiFeedbackProjectProjectIdGetErrors,
  GetProjectFeedbackApiFeedbackProjectProjectIdGetResponses,
  GetProjectShareStatusApiProjectsProjectIdShareGetData,
  GetProjectShareStatusApiProjectsProjectIdShareGetErrors,
  GetProjectShareStatusApiProjectsProjectIdShareGetResponses,
  GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetData,
  GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetErrors,
  GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponses,
  GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetData,
  GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetErrors,
  GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponses,
  GetRecentSelectionApiWorkflowTypesRecentSelectionGetData,
  GetRecentSelectionApiWorkflowTypesRecentSelectionGetResponses,
  GetSharedResourceApiPublicShareTokenGetData,
  GetSharedResourceApiPublicShareTokenGetErrors,
  GetSharedResourceApiPublicShareTokenGetResponses,
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetData,
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetErrors,
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponses,
  GetWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGetData,
  GetWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGetErrors,
  GetWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGetResponses,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetData,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetErrors,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponses,
  GetWorkflowTypesApiWorkflowTypesGetData,
  GetWorkflowTypesApiWorkflowTypesGetResponses,
  LinkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPostData,
  LinkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPostErrors,
  LinkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPostResponses,
  ListAppConfigsApiAppConfigsGetData,
  ListAppConfigsApiAppConfigsGetResponses,
  ListLogsApiAdminLogsGetData,
  ListLogsApiAdminLogsGetResponses,
  ListMessagesApiChatThreadsThreadIdMessagesGetData,
  ListMessagesApiChatThreadsThreadIdMessagesGetErrors,
  ListMessagesApiChatThreadsThreadIdMessagesGetResponses,
  ListProjectFilesEndpointApiProjectProjectIdFilesGetData,
  ListProjectFilesEndpointApiProjectProjectIdFilesGetErrors,
  ListProjectFilesEndpointApiProjectProjectIdFilesGetResponses,
  ListProjectsEndpointApiProjectsGetData,
  ListProjectsEndpointApiProjectsGetErrors,
  ListProjectsEndpointApiProjectsGetResponses,
  ListRevisionsEndpointApiProjectProjectIdRevisionsGetData,
  ListRevisionsEndpointApiProjectProjectIdRevisionsGetErrors,
  ListRevisionsEndpointApiProjectProjectIdRevisionsGetResponses,
  ListThreadsApiChatThreadsGetData,
  ListThreadsApiChatThreadsGetResponses,
  ListUsersApiUsersGetData,
  ListUsersApiUsersGetErrors,
  ListUsersApiUsersGetResponses,
  ReadHealthApiHealthGetData,
  ReadHealthApiHealthGetResponses,
  ReadHealthApiHealthHeadData,
  ReadHealthApiHealthHeadResponses,
  RemoveApiKeyApiUsersMeApiKeyDeleteData,
  RemoveApiKeyApiUsersMeApiKeyDeleteResponses,
  ResetAppConfigApiAppConfigsKeyDeleteData,
  ResetAppConfigApiAppConfigsKeyDeleteErrors,
  ResetAppConfigApiAppConfigsKeyDeleteResponses,
  ResolveIssueEndpointApiIssuesIssueIdResolvePostData,
  ResolveIssueEndpointApiIssuesIssueIdResolvePostErrors,
  ResolveIssueEndpointApiIssuesIssueIdResolvePostResponses,
  SetApiKeyApiUsersMeApiKeyPutData,
  SetApiKeyApiUsersMeApiKeyPutErrors,
  SetApiKeyApiUsersMeApiKeyPutResponses,
  StartMultipleWorkflowsApiWorkflowsStartMultiplePostData,
  StartMultipleWorkflowsApiWorkflowsStartMultiplePostErrors,
  StartMultipleWorkflowsApiWorkflowsStartMultiplePostResponses,
  StartWorkflowApiWorkflowsStartPostData,
  StartWorkflowApiWorkflowsStartPostErrors,
  StartWorkflowApiWorkflowsStartPostResponses,
  SubmitFeedbackApiFeedbackPostData,
  SubmitFeedbackApiFeedbackPostErrors,
  SubmitFeedbackApiFeedbackPostResponses,
  UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostData,
  UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostErrors,
  UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostResponses,
  UpdateAppConfigApiAppConfigsKeyPutData,
  UpdateAppConfigApiAppConfigsKeyPutErrors,
  UpdateAppConfigApiAppConfigsKeyPutResponses,
  UpdatePreferencesApiUsersMePreferencesPatchData,
  UpdatePreferencesApiUsersMePreferencesPatchErrors,
  UpdatePreferencesApiUsersMePreferencesPatchResponses,
  UpdateProjectEndpointApiProjectProjectIdPatchData,
  UpdateProjectEndpointApiProjectProjectIdPatchErrors,
  UpdateProjectEndpointApiProjectProjectIdPatchResponses,
  UpdateRoleApiUsersUserIdRolePatchData,
  UpdateRoleApiUsersUserIdRolePatchErrors,
  UpdateRoleApiUsersUserIdRolePatchResponses,
  UpdateThreadApiChatThreadsThreadIdPatchData,
  UpdateThreadApiChatThreadsThreadIdPatchErrors,
  UpdateThreadApiChatThreadsThreadIdPatchResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Read Health
 *
 * Health check endpoint — verifies database connectivity.
 */
export const readHealthApiHealthGet = <ThrowOnError extends boolean = true>(
  options?: Options<ReadHealthApiHealthGetData, ThrowOnError>,
): RequestResult<ReadHealthApiHealthGetResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<ReadHealthApiHealthGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/health',
    ...options,
  });

/**
 * Read Health
 *
 * Health check endpoint — verifies database connectivity.
 */
export const readHealthApiHealthHead = <ThrowOnError extends boolean = true>(
  options?: Options<ReadHealthApiHealthHeadData, ThrowOnError>,
): RequestResult<ReadHealthApiHealthHeadResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).head<ReadHealthApiHealthHeadResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/health',
    ...options,
  });

/**
 * Get About Content
 *
 * Return the About page markdown content (from the committed ABOUT.md).
 */
export const getAboutContentApiAboutGet = <ThrowOnError extends boolean = true>(
  options?: Options<GetAboutContentApiAboutGetData, ThrowOnError>,
): RequestResult<GetAboutContentApiAboutGetResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<GetAboutContentApiAboutGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/about',
    ...options,
  });

/**
 * Get Dashboard
 *
 * Usage aggregates for the admin dashboard over a rolling window.
 *
 * Counts are paired with the equal-length window that preceded them so the UI
 * can show a trend. Feedback is reported as counts only; text and authorship
 * remain behind the per-project visibility rules of `/api/admin/feedbacks`.
 *
 * Served from a short cache (see `_cached_dashboard`); the response carries
 * both the moment the figures were computed and the cache window, so the UI
 * can say how stale they may be.
 */
export const getDashboardApiAdminDashboardGet = <ThrowOnError extends boolean = true>(
  options?: Options<GetDashboardApiAdminDashboardGetData, ThrowOnError>,
): RequestResult<
  GetDashboardApiAdminDashboardGetResponses,
  GetDashboardApiAdminDashboardGetErrors,
  ThrowOnError,
  'data'
> =>
  (options?.client ?? client).get<
    GetDashboardApiAdminDashboardGetResponses,
    GetDashboardApiAdminDashboardGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/dashboard',
    ...options,
  });

/**
 * List App Configs
 *
 * List all application configs.
 */
export const listAppConfigsApiAppConfigsGet = <ThrowOnError extends boolean = true>(
  options?: Options<ListAppConfigsApiAppConfigsGetData, ThrowOnError>,
): RequestResult<ListAppConfigsApiAppConfigsGetResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<ListAppConfigsApiAppConfigsGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/app-configs',
    ...options,
  });

/**
 * Reset App Config
 *
 * Delete a config override (resets to code default).
 */
export const resetAppConfigApiAppConfigsKeyDelete = <ThrowOnError extends boolean = true>(
  options: Options<ResetAppConfigApiAppConfigsKeyDeleteData, ThrowOnError>,
): RequestResult<
  ResetAppConfigApiAppConfigsKeyDeleteResponses,
  ResetAppConfigApiAppConfigsKeyDeleteErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).delete<
    ResetAppConfigApiAppConfigsKeyDeleteResponses,
    ResetAppConfigApiAppConfigsKeyDeleteErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/app-configs/{key}',
    ...options,
  });

/**
 * Get App Config
 *
 * Return the value for a single config key. Public endpoint, no auth required.
 */
export const getAppConfigApiAppConfigsKeyGet = <ThrowOnError extends boolean = true>(
  options: Options<GetAppConfigApiAppConfigsKeyGetData, ThrowOnError>,
): RequestResult<
  GetAppConfigApiAppConfigsKeyGetResponses,
  GetAppConfigApiAppConfigsKeyGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetAppConfigApiAppConfigsKeyGetResponses,
    GetAppConfigApiAppConfigsKeyGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    url: '/api/app-configs/{key}',
    ...options,
  });

/**
 * Update App Config
 *
 * Create or update an application config value.
 */
export const updateAppConfigApiAppConfigsKeyPut = <ThrowOnError extends boolean = true>(
  options: Options<UpdateAppConfigApiAppConfigsKeyPutData, ThrowOnError>,
): RequestResult<
  UpdateAppConfigApiAppConfigsKeyPutResponses,
  UpdateAppConfigApiAppConfigsKeyPutErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).put<
    UpdateAppConfigApiAppConfigsKeyPutResponses,
    UpdateAppConfigApiAppConfigsKeyPutErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/app-configs/{key}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Threads
 */
export const listThreadsApiChatThreadsGet = <ThrowOnError extends boolean = true>(
  options?: Options<ListThreadsApiChatThreadsGetData, ThrowOnError>,
): RequestResult<ListThreadsApiChatThreadsGetResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<ListThreadsApiChatThreadsGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/chat/threads',
    ...options,
  });

/**
 * Create Thread
 */
export const createThreadApiChatThreadsPost = <ThrowOnError extends boolean = true>(
  options: Options<CreateThreadApiChatThreadsPostData, ThrowOnError>,
): RequestResult<CreateThreadApiChatThreadsPostResponses, CreateThreadApiChatThreadsPostErrors, ThrowOnError, 'data'> =>
  (options.client ?? client).post<
    CreateThreadApiChatThreadsPostResponses,
    CreateThreadApiChatThreadsPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/chat/threads',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Thread
 */
export const deleteThreadApiChatThreadsThreadIdDelete = <ThrowOnError extends boolean = true>(
  options: Options<DeleteThreadApiChatThreadsThreadIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteThreadApiChatThreadsThreadIdDeleteResponses,
  DeleteThreadApiChatThreadsThreadIdDeleteErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).delete<
    DeleteThreadApiChatThreadsThreadIdDeleteResponses,
    DeleteThreadApiChatThreadsThreadIdDeleteErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/chat/threads/{thread_id}',
    ...options,
  });

/**
 * Update Thread
 */
export const updateThreadApiChatThreadsThreadIdPatch = <ThrowOnError extends boolean = true>(
  options: Options<UpdateThreadApiChatThreadsThreadIdPatchData, ThrowOnError>,
): RequestResult<
  UpdateThreadApiChatThreadsThreadIdPatchResponses,
  UpdateThreadApiChatThreadsThreadIdPatchErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).patch<
    UpdateThreadApiChatThreadsThreadIdPatchResponses,
    UpdateThreadApiChatThreadsThreadIdPatchErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/chat/threads/{thread_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Messages
 */
export const listMessagesApiChatThreadsThreadIdMessagesGet = <ThrowOnError extends boolean = true>(
  options: Options<ListMessagesApiChatThreadsThreadIdMessagesGetData, ThrowOnError>,
): RequestResult<
  ListMessagesApiChatThreadsThreadIdMessagesGetResponses,
  ListMessagesApiChatThreadsThreadIdMessagesGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    ListMessagesApiChatThreadsThreadIdMessagesGetResponses,
    ListMessagesApiChatThreadsThreadIdMessagesGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/chat/threads/{thread_id}/messages',
    ...options,
  });

/**
 * Append Message
 */
export const appendMessageApiChatThreadsThreadIdMessagesPost = <ThrowOnError extends boolean = true>(
  options: Options<AppendMessageApiChatThreadsThreadIdMessagesPostData, ThrowOnError>,
): RequestResult<
  AppendMessageApiChatThreadsThreadIdMessagesPostResponses,
  AppendMessageApiChatThreadsThreadIdMessagesPostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    AppendMessageApiChatThreadsThreadIdMessagesPostResponses,
    AppendMessageApiChatThreadsThreadIdMessagesPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/chat/threads/{thread_id}/messages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Check Preflight
 *
 * Run preflight validation before starting analysis.
 */
export const checkPreflightApiPreflightPost = <ThrowOnError extends boolean = true>(
  options: Options<CheckPreflightApiPreflightPostData, ThrowOnError>,
): RequestResult<CheckPreflightApiPreflightPostResponses, CheckPreflightApiPreflightPostErrors, ThrowOnError, 'data'> =>
  (options.client ?? client).post<
    CheckPreflightApiPreflightPostResponses,
    CheckPreflightApiPreflightPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/preflight',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Start Workflow
 *
 * Start a workflow
 */
export const startWorkflowApiWorkflowsStartPost = <ThrowOnError extends boolean = true>(
  options: Options<StartWorkflowApiWorkflowsStartPostData, ThrowOnError>,
): RequestResult<
  StartWorkflowApiWorkflowsStartPostResponses,
  StartWorkflowApiWorkflowsStartPostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    StartWorkflowApiWorkflowsStartPostResponses,
    StartWorkflowApiWorkflowsStartPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflows/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Start Multiple Workflows
 *
 * Start multiple workflow analyses for a project.
 */
export const startMultipleWorkflowsApiWorkflowsStartMultiplePost = <ThrowOnError extends boolean = true>(
  options: Options<StartMultipleWorkflowsApiWorkflowsStartMultiplePostData, ThrowOnError>,
): RequestResult<
  StartMultipleWorkflowsApiWorkflowsStartMultiplePostResponses,
  StartMultipleWorkflowsApiWorkflowsStartMultiplePostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    StartMultipleWorkflowsApiWorkflowsStartMultiplePostResponses,
    StartMultipleWorkflowsApiWorkflowsStartMultiplePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflows/start-multiple',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Workflow State
 *
 * Get the state of a workflow
 */
export const getWorkflowStateApiWorkflowsWorkflowRunIdGet = <ThrowOnError extends boolean = true>(
  options: Options<GetWorkflowStateApiWorkflowsWorkflowRunIdGetData, ThrowOnError>,
): RequestResult<
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponses,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponses,
    GetWorkflowStateApiWorkflowsWorkflowRunIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflows/{workflow_run_id}',
    ...options,
  });

/**
 * Get Workflow Raw State
 *
 * The run's persisted state exactly as stored, bypassing the state model.
 *
 * Served on its own route rather than inlined into the run listings: payloads
 * reach several MB, and this is only ever needed for the one run a user is
 * looking at. The UI offers it when a run's state no longer validates against
 * the current model, so the data is still recoverable after an assessment
 * changes shape.
 *
 * Authorized through `get_project_access` rather than ownership alone, so the
 * escape hatch works on a share link too. A shared viewer is already served
 * this run's parsed state in the project response; that it is unreadable is a
 * parsing failure, not a narrower grant.
 */
export const getWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGet = <ThrowOnError extends boolean = true>(
  options: Options<GetWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGetData, ThrowOnError>,
): RequestResult<
  GetWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGetResponses,
  GetWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGetResponses,
    GetWorkflowRawStateApiWorkflowsWorkflowRunIdRawStateGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflows/{workflow_run_id}/raw-state',
    ...options,
  });

/**
 * Approve Project Gate Endpoint
 *
 * Approve a workflow gate for the project's current revision.
 *
 * Records the approval and schedules every run in AWAITING_APPROVAL that
 * was waiting on this gate (e.g. Claim Reference Validation behind the
 * reference review). Approving an already-approved gate is a no-op.
 */
export const approveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePost = <ThrowOnError extends boolean = true>(
  options: Options<ApproveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePostData, ThrowOnError>,
): RequestResult<
  ApproveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePostResponses,
  ApproveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    ApproveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePostResponses,
    ApproveProjectGateEndpointApiProjectsProjectIdGatesGateApprovePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/gates/{gate}/approve',
    ...options,
  });

/**
 * Cancel Workflow Run Endpoint
 *
 * Cancel a workflow run that is pending or running.
 *
 * Cascades cancellation to any active workflow runs that have the cancelled
 * workflow as a required dependency.
 */
export const cancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPost = <ThrowOnError extends boolean = true>(
  options: Options<CancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPostData, ThrowOnError>,
): RequestResult<
  CancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPostResponses,
  CancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    CancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPostResponses,
    CancelWorkflowRunEndpointApiWorkflowRunsWorkflowRunIdCancelPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflow-runs/{workflow_run_id}/cancel',
    ...options,
  });

/**
 * Get Workflow Types
 *
 * List available workflow types and the ordered category display config.
 */
export const getWorkflowTypesApiWorkflowTypesGet = <ThrowOnError extends boolean = true>(
  options?: Options<GetWorkflowTypesApiWorkflowTypesGetData, ThrowOnError>,
): RequestResult<GetWorkflowTypesApiWorkflowTypesGetResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<GetWorkflowTypesApiWorkflowTypesGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/workflow-types',
    ...options,
  });

/**
 * Get Recent Selection
 *
 * Assessments this user ran on their most recent project.
 *
 * Seeds the new-project wizard's pre-selection with what the user actually
 * reaches for. Unlike the listing above this is per-user, so it requires auth.
 * Deliberately uncached: it is two indexed queries, and it has to reflect the
 * project the user just finished.
 */
export const getRecentSelectionApiWorkflowTypesRecentSelectionGet = <ThrowOnError extends boolean = true>(
  options?: Options<GetRecentSelectionApiWorkflowTypesRecentSelectionGetData, ThrowOnError>,
): RequestResult<GetRecentSelectionApiWorkflowTypesRecentSelectionGetResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<
    GetRecentSelectionApiWorkflowTypesRecentSelectionGetResponses,
    unknown,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflow-types/recent-selection',
    ...options,
  });

/**
 * Get Duration Estimates
 *
 * Estimated run duration for every workflow type, derived from past runs.
 *
 * Lets the UI show a ballpark "how long will this take" before a workflow is
 * started. `project_id` is accepted for future project-specific refinement but
 * is not yet factored into the estimate. The response is cached for an hour at
 * the endpoint layer (see `_cached_duration_estimates`).
 */
export const getDurationEstimatesApiWorkflowTypesDurationEstimatesGet = <ThrowOnError extends boolean = true>(
  options: Options<GetDurationEstimatesApiWorkflowTypesDurationEstimatesGetData, ThrowOnError>,
): RequestResult<
  GetDurationEstimatesApiWorkflowTypesDurationEstimatesGetResponses,
  GetDurationEstimatesApiWorkflowTypesDurationEstimatesGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetDurationEstimatesApiWorkflowTypesDurationEstimatesGetResponses,
    GetDurationEstimatesApiWorkflowTypesDurationEstimatesGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflow-types/duration-estimates',
    ...options,
  });

/**
 * Download File
 *
 * Download a file by ID with access control.
 *
 * This endpoint supports two access modes:
 * 1. Authenticated access: User must own the project containing the file
 * 2. Share token access: Valid share token for the project grants read access
 *
 * Args:
 * file_id: UUID of the file to download
 * share_token: Optional share token for unauthenticated access
 * current_user: Authenticated user from JWT token (optional when share_token provided)
 *
 * Returns:
 * FileResponse with the file contents
 *
 * Raises:
 * HTTPException: 400 for invalid file ID, 401 if not authenticated, 404 if file not found, 403 if access denied
 */
export const downloadFileApiFilesDownloadFileIdGet = <ThrowOnError extends boolean = true>(
  options: Options<DownloadFileApiFilesDownloadFileIdGetData, ThrowOnError>,
): RequestResult<
  DownloadFileApiFilesDownloadFileIdGetResponses,
  DownloadFileApiFilesDownloadFileIdGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    DownloadFileApiFilesDownloadFileIdGetResponses,
    DownloadFileApiFilesDownloadFileIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/files/download/{file_id}',
    ...options,
  });

/**
 * Get Feedback
 *
 * Get feedback for a specific entity or issue
 *
 * Examples:
 * - GET /api/feedback?workflow_run_id=xxx&entity_path={"chunk_index":0,"claim_index":1}
 * - GET /api/feedback?issue_id=xxx
 */
export const getFeedbackApiFeedbackGet = <ThrowOnError extends boolean = true>(
  options?: Options<GetFeedbackApiFeedbackGetData, ThrowOnError>,
): RequestResult<GetFeedbackApiFeedbackGetResponses, GetFeedbackApiFeedbackGetErrors, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<
    GetFeedbackApiFeedbackGetResponses,
    GetFeedbackApiFeedbackGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback',
    ...options,
  });

/**
 * Submit Feedback
 *
 * Submit or update feedback for any entity
 */
export const submitFeedbackApiFeedbackPost = <ThrowOnError extends boolean = true>(
  options: Options<SubmitFeedbackApiFeedbackPostData, ThrowOnError>,
): RequestResult<SubmitFeedbackApiFeedbackPostResponses, SubmitFeedbackApiFeedbackPostErrors, ThrowOnError, 'data'> =>
  (options.client ?? client).post<
    SubmitFeedbackApiFeedbackPostResponses,
    SubmitFeedbackApiFeedbackPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Workflow Feedback
 *
 * Get all feedback for a workflow run
 */
export const getWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGet = <ThrowOnError extends boolean = true>(
  options: Options<GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetData, ThrowOnError>,
): RequestResult<
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponses,
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponses,
    GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback/workflow/{workflow_run_id}',
    ...options,
  });

/**
 * Get Project Feedback
 *
 * Get all issue feedback for a project (single call for all issues)
 */
export const getProjectFeedbackApiFeedbackProjectProjectIdGet = <ThrowOnError extends boolean = true>(
  options: Options<GetProjectFeedbackApiFeedbackProjectProjectIdGetData, ThrowOnError>,
): RequestResult<
  GetProjectFeedbackApiFeedbackProjectProjectIdGetResponses,
  GetProjectFeedbackApiFeedbackProjectProjectIdGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetProjectFeedbackApiFeedbackProjectProjectIdGetResponses,
    GetProjectFeedbackApiFeedbackProjectProjectIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback/project/{project_id}',
    ...options,
  });

/**
 * Get Admin Feedbacks
 *
 * Get all shared feedback for admin view. Only returns feedback from projects
 * where the user has set visibility to issue_only or full_project.
 */
export const getAdminFeedbacksApiAdminFeedbacksGet = <ThrowOnError extends boolean = true>(
  options?: Options<GetAdminFeedbacksApiAdminFeedbacksGetData, ThrowOnError>,
): RequestResult<
  GetAdminFeedbacksApiAdminFeedbacksGetResponses,
  GetAdminFeedbacksApiAdminFeedbacksGetErrors,
  ThrowOnError,
  'data'
> =>
  (options?.client ?? client).get<
    GetAdminFeedbacksApiAdminFeedbacksGetResponses,
    GetAdminFeedbacksApiAdminFeedbacksGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/feedbacks',
    ...options,
  });

/**
 * Export Admin Feedbacks Csv
 *
 * Export all shared feedback as a CSV file.
 */
export const exportAdminFeedbacksCsvApiAdminFeedbacksExportGet = <ThrowOnError extends boolean = true>(
  options?: Options<ExportAdminFeedbacksCsvApiAdminFeedbacksExportGetData, ThrowOnError>,
): RequestResult<
  ExportAdminFeedbacksCsvApiAdminFeedbacksExportGetResponses,
  ExportAdminFeedbacksCsvApiAdminFeedbacksExportGetErrors,
  ThrowOnError,
  'data'
> =>
  (options?.client ?? client).get<
    ExportAdminFeedbacksCsvApiAdminFeedbacksExportGetResponses,
    ExportAdminFeedbacksCsvApiAdminFeedbacksExportGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/feedbacks/export',
    ...options,
  });

/**
 * Delete Feedback
 *
 * Delete feedback by ID
 */
export const deleteFeedbackApiFeedbackFeedbackIdDelete = <ThrowOnError extends boolean = true>(
  options: Options<DeleteFeedbackApiFeedbackFeedbackIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteFeedbackApiFeedbackFeedbackIdDeleteResponses,
  DeleteFeedbackApiFeedbackFeedbackIdDeleteErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).delete<
    DeleteFeedbackApiFeedbackFeedbackIdDeleteResponses,
    DeleteFeedbackApiFeedbackFeedbackIdDeleteErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback/{feedback_id}',
    ...options,
  });

/**
 * List Logs
 *
 * Return metadata for all available log files, newest first.
 */
export const listLogsApiAdminLogsGet = <ThrowOnError extends boolean = true>(
  options?: Options<ListLogsApiAdminLogsGetData, ThrowOnError>,
): RequestResult<ListLogsApiAdminLogsGetResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<ListLogsApiAdminLogsGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/logs',
    ...options,
  });

/**
 * Download Log
 *
 * Download a specific log file by name.
 */
export const downloadLogApiAdminLogsDownloadFilenameGet = <ThrowOnError extends boolean = true>(
  options: Options<DownloadLogApiAdminLogsDownloadFilenameGetData, ThrowOnError>,
): RequestResult<
  DownloadLogApiAdminLogsDownloadFilenameGetResponses,
  DownloadLogApiAdminLogsDownloadFilenameGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    DownloadLogApiAdminLogsDownloadFilenameGetResponses,
    DownloadLogApiAdminLogsDownloadFilenameGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/admin/logs/download/{filename}',
    ...options,
  });

/**
 * Resolve Issue Endpoint
 *
 * Mark an issue as resolved.
 */
export const resolveIssueEndpointApiIssuesIssueIdResolvePost = <ThrowOnError extends boolean = true>(
  options: Options<ResolveIssueEndpointApiIssuesIssueIdResolvePostData, ThrowOnError>,
): RequestResult<
  ResolveIssueEndpointApiIssuesIssueIdResolvePostResponses,
  ResolveIssueEndpointApiIssuesIssueIdResolvePostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    ResolveIssueEndpointApiIssuesIssueIdResolvePostResponses,
    ResolveIssueEndpointApiIssuesIssueIdResolvePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{issue_id}/resolve',
    ...options,
  });

/**
 * Unresolve Issue Endpoint
 *
 * Mark an issue as unresolved.
 */
export const unresolveIssueEndpointApiIssuesIssueIdUnresolvePost = <ThrowOnError extends boolean = true>(
  options: Options<UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostData, ThrowOnError>,
): RequestResult<
  UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostResponses,
  UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostResponses,
    UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{issue_id}/unresolve',
    ...options,
  });

/**
 * Get Issue Endpoint
 *
 * Get a single issue by ID.
 */
export const getIssueEndpointApiIssuesIssueIdGet = <ThrowOnError extends boolean = true>(
  options: Options<GetIssueEndpointApiIssuesIssueIdGetData, ThrowOnError>,
): RequestResult<
  GetIssueEndpointApiIssuesIssueIdGetResponses,
  GetIssueEndpointApiIssuesIssueIdGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetIssueEndpointApiIssuesIssueIdGetResponses,
    GetIssueEndpointApiIssuesIssueIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/issues/{issue_id}',
    ...options,
  });

/**
 * List Projects Endpoint
 *
 * List the current user's projects, newest activity first, one page at a time.
 */
export const listProjectsEndpointApiProjectsGet = <ThrowOnError extends boolean = true>(
  options?: Options<ListProjectsEndpointApiProjectsGetData, ThrowOnError>,
): RequestResult<
  ListProjectsEndpointApiProjectsGetResponses,
  ListProjectsEndpointApiProjectsGetErrors,
  ThrowOnError,
  'data'
> =>
  (options?.client ?? client).get<
    ListProjectsEndpointApiProjectsGetResponses,
    ListProjectsEndpointApiProjectsGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects',
    ...options,
  });

/**
 * Create Project Endpoint
 *
 * Create a project.
 *
 * This endpoint creates the project first, then files are uploaded
 * separately via the /api/upload endpoints.
 */
export const createProjectEndpointApiProjectsPost = <ThrowOnError extends boolean = true>(
  options: Options<CreateProjectEndpointApiProjectsPostData, ThrowOnError>,
): RequestResult<
  CreateProjectEndpointApiProjectsPostResponses,
  CreateProjectEndpointApiProjectsPostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    CreateProjectEndpointApiProjectsPostResponses,
    CreateProjectEndpointApiProjectsPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Project Endpoint
 *
 * Delete a project and all associated results
 */
export const deleteProjectEndpointApiProjectProjectIdDelete = <ThrowOnError extends boolean = true>(
  options: Options<DeleteProjectEndpointApiProjectProjectIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteProjectEndpointApiProjectProjectIdDeleteResponses,
  DeleteProjectEndpointApiProjectProjectIdDeleteErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).delete<
    DeleteProjectEndpointApiProjectProjectIdDeleteResponses,
    DeleteProjectEndpointApiProjectProjectIdDeleteErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}',
    ...options,
  });

/**
 * Get Project Endpoint
 *
 * Get a project by ID. Set include_internal=true to see internal workflows.
 */
export const getProjectEndpointApiProjectProjectIdGet = <ThrowOnError extends boolean = true>(
  options: Options<GetProjectEndpointApiProjectProjectIdGetData, ThrowOnError>,
): RequestResult<
  GetProjectEndpointApiProjectProjectIdGetResponses,
  GetProjectEndpointApiProjectProjectIdGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetProjectEndpointApiProjectProjectIdGetResponses,
    GetProjectEndpointApiProjectProjectIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}',
    ...options,
  });

/**
 * Update Project Endpoint
 *
 * Update a project with the provided fields
 */
export const updateProjectEndpointApiProjectProjectIdPatch = <ThrowOnError extends boolean = true>(
  options: Options<UpdateProjectEndpointApiProjectProjectIdPatchData, ThrowOnError>,
): RequestResult<
  UpdateProjectEndpointApiProjectProjectIdPatchResponses,
  UpdateProjectEndpointApiProjectProjectIdPatchErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).patch<
    UpdateProjectEndpointApiProjectProjectIdPatchResponses,
    UpdateProjectEndpointApiProjectProjectIdPatchErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Download Project Docx
 *
 * Download DOCX with AI comments. Always regenerates from scratch.
 */
export const downloadProjectDocxApiProjectsProjectIdDocxDownloadGet = <ThrowOnError extends boolean = true>(
  options: Options<DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetData, ThrowOnError>,
): RequestResult<
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetResponses,
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetResponses,
    DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/docx/download',
    ...options,
  });

/**
 * List Project Files Endpoint
 *
 * Get all files for a project
 */
export const listProjectFilesEndpointApiProjectProjectIdFilesGet = <ThrowOnError extends boolean = true>(
  options: Options<ListProjectFilesEndpointApiProjectProjectIdFilesGetData, ThrowOnError>,
): RequestResult<
  ListProjectFilesEndpointApiProjectProjectIdFilesGetResponses,
  ListProjectFilesEndpointApiProjectProjectIdFilesGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    ListProjectFilesEndpointApiProjectProjectIdFilesGetResponses,
    ListProjectFilesEndpointApiProjectProjectIdFilesGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}/files',
    ...options,
  });

/**
 * Delete Project File Endpoint
 *
 * Delete a file from a project and unlink it from any references.
 */
export const deleteProjectFileEndpointApiProjectProjectIdFilesFileIdDelete = <ThrowOnError extends boolean = true>(
  options: Options<DeleteProjectFileEndpointApiProjectProjectIdFilesFileIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteProjectFileEndpointApiProjectProjectIdFilesFileIdDeleteResponses,
  DeleteProjectFileEndpointApiProjectProjectIdFilesFileIdDeleteErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).delete<
    DeleteProjectFileEndpointApiProjectProjectIdFilesFileIdDeleteResponses,
    DeleteProjectFileEndpointApiProjectProjectIdFilesFileIdDeleteErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}/files/{file_id}',
    ...options,
  });

/**
 * Link Reference File Endpoint
 *
 * Link an already-uploaded supporting file to an extracted reference.
 *
 * The app can already do this at upload time, by putting a `reference_id` in
 * the TUS metadata. This is the same operation for a file that is already in
 * the project, so a user can correct or supply a match without re-uploading.
 *
 * The link is recorded as `MANUAL_UPLOAD`, which takes precedence over
 * whatever the automatic matcher decided. Re-posting for the same reference
 * replaces the previous match rather than adding a second one.
 */
export const linkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPost = <
  ThrowOnError extends boolean = true,
>(
  options: Options<LinkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPostData, ThrowOnError>,
): RequestResult<
  LinkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPostResponses,
  LinkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    LinkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPostResponses,
    LinkReferenceFileEndpointApiProjectProjectIdReferencesReferenceIdFilesPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}/references/{reference_id}/files',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Download All Project Files
 *
 * Download all project files as a ZIP archive
 */
export const downloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGet = <ThrowOnError extends boolean = true>(
  options: Options<DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetData, ThrowOnError>,
): RequestResult<
  DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetResponses,
  DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetResponses,
    DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}/files/download-all',
    ...options,
  });

/**
 * Get Project Workflow Progress Endpoint
 *
 * Get all workflow progress entries for a project.
 */
export const getProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGet = <
  ThrowOnError extends boolean = true,
>(
  options: Options<GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetData, ThrowOnError>,
): RequestResult<
  GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponses,
  GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponses,
    GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}/workflow-progress',
    ...options,
  });

/**
 * Get Project Workflow Runs By Type Endpoint
 *
 * Get all workflow runs of a specific type for a project.
 *
 * Returns workflow run details (including state with errors) ordered by creation date descending.
 * Used for displaying workflow run history in the UI with correct error status.
 */
export const getProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGet = <
  ThrowOnError extends boolean = true,
>(
  options: Options<GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetData, ThrowOnError>,
): RequestResult<
  GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponses,
  GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponses,
    GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}/workflow-runs',
    ...options,
  });

/**
 * List Revisions Endpoint
 *
 * List all revisions for a project with their main file info.
 */
export const listRevisionsEndpointApiProjectProjectIdRevisionsGet = <ThrowOnError extends boolean = true>(
  options: Options<ListRevisionsEndpointApiProjectProjectIdRevisionsGetData, ThrowOnError>,
): RequestResult<
  ListRevisionsEndpointApiProjectProjectIdRevisionsGetResponses,
  ListRevisionsEndpointApiProjectProjectIdRevisionsGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    ListRevisionsEndpointApiProjectProjectIdRevisionsGetResponses,
    ListRevisionsEndpointApiProjectProjectIdRevisionsGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}/revisions',
    ...options,
  });

/**
 * Create Revision Endpoint
 *
 * Create a new revision for a project.
 *
 * Archives active issues from the current revision, cancels running workflows,
 * and increments the revision counter. The new main document should be uploaded
 * via the TUS upload endpoint after this call.
 */
export const createRevisionEndpointApiProjectProjectIdRevisionsPost = <ThrowOnError extends boolean = true>(
  options: Options<CreateRevisionEndpointApiProjectProjectIdRevisionsPostData, ThrowOnError>,
): RequestResult<
  CreateRevisionEndpointApiProjectProjectIdRevisionsPostResponses,
  CreateRevisionEndpointApiProjectProjectIdRevisionsPostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    CreateRevisionEndpointApiProjectProjectIdRevisionsPostResponses,
    CreateRevisionEndpointApiProjectProjectIdRevisionsPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}/revisions',
    ...options,
  });

/**
 * Get Project Share Status
 *
 * Get the sharing status for a project.
 */
export const getProjectShareStatusApiProjectsProjectIdShareGet = <ThrowOnError extends boolean = true>(
  options: Options<GetProjectShareStatusApiProjectsProjectIdShareGetData, ThrowOnError>,
): RequestResult<
  GetProjectShareStatusApiProjectsProjectIdShareGetResponses,
  GetProjectShareStatusApiProjectsProjectIdShareGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetProjectShareStatusApiProjectsProjectIdShareGetResponses,
    GetProjectShareStatusApiProjectsProjectIdShareGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/share',
    ...options,
  });

/**
 * Enable Project Sharing
 *
 * Enable sharing for a project (creates a share link if none exists).
 */
export const enableProjectSharingApiProjectsProjectIdShareEnablePost = <ThrowOnError extends boolean = true>(
  options: Options<EnableProjectSharingApiProjectsProjectIdShareEnablePostData, ThrowOnError>,
): RequestResult<
  EnableProjectSharingApiProjectsProjectIdShareEnablePostResponses,
  EnableProjectSharingApiProjectsProjectIdShareEnablePostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    EnableProjectSharingApiProjectsProjectIdShareEnablePostResponses,
    EnableProjectSharingApiProjectsProjectIdShareEnablePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/share/enable',
    ...options,
  });

/**
 * Disable Project Sharing
 *
 * Disable sharing for a project (deactivates the share link).
 */
export const disableProjectSharingApiProjectsProjectIdShareDisablePost = <ThrowOnError extends boolean = true>(
  options: Options<DisableProjectSharingApiProjectsProjectIdShareDisablePostData, ThrowOnError>,
): RequestResult<
  DisableProjectSharingApiProjectsProjectIdShareDisablePostResponses,
  DisableProjectSharingApiProjectsProjectIdShareDisablePostErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).post<
    DisableProjectSharingApiProjectsProjectIdShareDisablePostResponses,
    DisableProjectSharingApiProjectsProjectIdShareDisablePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/share/disable',
    ...options,
  });

/**
 * Get Shared Resource
 *
 * Access a shared resource by token.
 *
 * This endpoint does not require authentication - the token IS the auth.
 * Returns project info and workflow state in a single call.
 */
export const getSharedResourceApiPublicShareTokenGet = <ThrowOnError extends boolean = true>(
  options: Options<GetSharedResourceApiPublicShareTokenGetData, ThrowOnError>,
): RequestResult<
  GetSharedResourceApiPublicShareTokenGetResponses,
  GetSharedResourceApiPublicShareTokenGetErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).get<
    GetSharedResourceApiPublicShareTokenGetResponses,
    GetSharedResourceApiPublicShareTokenGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    url: '/api/public/share/{token}',
    ...options,
  });

/**
 * Extension Termination Route
 */
export const extensionTerminationRouteTusUuidDelete = <ThrowOnError extends boolean = true>(
  options: Options<ExtensionTerminationRouteTusUuidDeleteData, ThrowOnError>,
): RequestResult<
  ExtensionTerminationRouteTusUuidDeleteResponses,
  ExtensionTerminationRouteTusUuidDeleteErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).delete<
    ExtensionTerminationRouteTusUuidDeleteResponses,
    ExtensionTerminationRouteTusUuidDeleteErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tus/{uuid}',
    ...options,
  });

/**
 * Core Head Route
 */
export const coreHeadRouteTusUuidHead = <ThrowOnError extends boolean = true>(
  options: Options<CoreHeadRouteTusUuidHeadData, ThrowOnError>,
): RequestResult<CoreHeadRouteTusUuidHeadResponses, CoreHeadRouteTusUuidHeadErrors, ThrowOnError, 'data'> =>
  (options.client ?? client).head<
    CoreHeadRouteTusUuidHeadResponses,
    CoreHeadRouteTusUuidHeadErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tus/{uuid}',
    ...options,
  });

/**
 * Core Patch Route
 */
export const corePatchRouteTusUuidPatch = <ThrowOnError extends boolean = true>(
  options: Options<CorePatchRouteTusUuidPatchData, ThrowOnError>,
): RequestResult<CorePatchRouteTusUuidPatchResponses, CorePatchRouteTusUuidPatchErrors, ThrowOnError, 'data'> =>
  (options.client ?? client).patch<
    CorePatchRouteTusUuidPatchResponses,
    CorePatchRouteTusUuidPatchErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tus/{uuid}',
    ...options,
  });

/**
 * Core Options Route
 */
export const coreOptionsRouteTusOptions = <ThrowOnError extends boolean = true>(
  options?: Options<CoreOptionsRouteTusOptionsData, ThrowOnError>,
): RequestResult<CoreOptionsRouteTusOptionsResponses, CoreOptionsRouteTusOptionsErrors, ThrowOnError, 'data'> =>
  (options?.client ?? client).options<
    CoreOptionsRouteTusOptionsResponses,
    CoreOptionsRouteTusOptionsErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tus/',
    ...options,
  });

/**
 * Extension Creation Route
 */
export const extensionCreationRouteTusPost = <ThrowOnError extends boolean = true>(
  options?: Options<ExtensionCreationRouteTusPostData, ThrowOnError>,
): RequestResult<ExtensionCreationRouteTusPostResponses, ExtensionCreationRouteTusPostErrors, ThrowOnError, 'data'> =>
  (options?.client ?? client).post<
    ExtensionCreationRouteTusPostResponses,
    ExtensionCreationRouteTusPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tus/',
    ...options,
  });

/**
 * Extension Creation Route
 */
export const extensionCreationRouteTusPost2 = <ThrowOnError extends boolean = true>(
  options?: Options<ExtensionCreationRouteTusPost2Data, ThrowOnError>,
): RequestResult<ExtensionCreationRouteTusPost2Responses, ExtensionCreationRouteTusPost2Errors, ThrowOnError, 'data'> =>
  (options?.client ?? client).post<
    ExtensionCreationRouteTusPost2Responses,
    ExtensionCreationRouteTusPost2Errors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tus',
    ...options,
  });

/**
 * Get Current User Info
 *
 * Get the current authenticated user's information.
 */
export const getCurrentUserInfoApiUsersMeGet = <ThrowOnError extends boolean = true>(
  options?: Options<GetCurrentUserInfoApiUsersMeGetData, ThrowOnError>,
): RequestResult<GetCurrentUserInfoApiUsersMeGetResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<GetCurrentUserInfoApiUsersMeGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/me',
    ...options,
  });

/**
 * List Users
 *
 * List users (admin only), optionally filtered by name, email, or role.
 */
export const listUsersApiUsersGet = <ThrowOnError extends boolean = true>(
  options?: Options<ListUsersApiUsersGetData, ThrowOnError>,
): RequestResult<ListUsersApiUsersGetResponses, ListUsersApiUsersGetErrors, ThrowOnError, 'data'> =>
  (options?.client ?? client).get<ListUsersApiUsersGetResponses, ListUsersApiUsersGetErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users',
    ...options,
  });

/**
 * Update Role
 *
 * Update a user's role (admin only).
 */
export const updateRoleApiUsersUserIdRolePatch = <ThrowOnError extends boolean = true>(
  options: Options<UpdateRoleApiUsersUserIdRolePatchData, ThrowOnError>,
): RequestResult<
  UpdateRoleApiUsersUserIdRolePatchResponses,
  UpdateRoleApiUsersUserIdRolePatchErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).patch<
    UpdateRoleApiUsersUserIdRolePatchResponses,
    UpdateRoleApiUsersUserIdRolePatchErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{user_id}/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Preferences
 *
 * Update the current user's preferences.
 */
export const updatePreferencesApiUsersMePreferencesPatch = <ThrowOnError extends boolean = true>(
  options: Options<UpdatePreferencesApiUsersMePreferencesPatchData, ThrowOnError>,
): RequestResult<
  UpdatePreferencesApiUsersMePreferencesPatchResponses,
  UpdatePreferencesApiUsersMePreferencesPatchErrors,
  ThrowOnError,
  'data'
> =>
  (options.client ?? client).patch<
    UpdatePreferencesApiUsersMePreferencesPatchResponses,
    UpdatePreferencesApiUsersMePreferencesPatchErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/me/preferences',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Api Key
 *
 * Remove the stored OpenAI API key for the current user.
 */
export const removeApiKeyApiUsersMeApiKeyDelete = <ThrowOnError extends boolean = true>(
  options?: Options<RemoveApiKeyApiUsersMeApiKeyDeleteData, ThrowOnError>,
): RequestResult<RemoveApiKeyApiUsersMeApiKeyDeleteResponses, unknown, ThrowOnError, 'data'> =>
  (options?.client ?? client).delete<RemoveApiKeyApiUsersMeApiKeyDeleteResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/me/api-key',
    ...options,
  });

/**
 * Set Api Key
 *
 * Validate and store an OpenAI API key for the current user.
 */
export const setApiKeyApiUsersMeApiKeyPut = <ThrowOnError extends boolean = true>(
  options: Options<SetApiKeyApiUsersMeApiKeyPutData, ThrowOnError>,
): RequestResult<SetApiKeyApiUsersMeApiKeyPutResponses, SetApiKeyApiUsersMeApiKeyPutErrors, ThrowOnError, 'data'> =>
  (options.client ?? client).put<
    SetApiKeyApiUsersMeApiKeyPutResponses,
    SetApiKeyApiUsersMeApiKeyPutErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/me/api-key',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Bot Messages
 *
 * The bot's messaging endpoint, called by the Bot Connector.
 *
 * The turn acknowledges and ends; the answer follows about a minute later into
 * the same thread. Keeping the request short is what lets Teams show a reply
 * immediately instead of waiting on the model.
 *
 * Outside ``get_current_user``: the Bot Connector presents its own token, which
 * the Agents SDK validates. That token is the authentication.
 */
export const botMessagesApiMicrosoftTeamsMessagesPost = <ThrowOnError extends boolean = true>(
  options?: Options<BotMessagesApiMicrosoftTeamsMessagesPostData, ThrowOnError>,
): RequestResult<
  BotMessagesApiMicrosoftTeamsMessagesPostResponses,
  BotMessagesApiMicrosoftTeamsMessagesPostErrors,
  ThrowOnError,
  'data'
> =>
  (options?.client ?? client).post<
    BotMessagesApiMicrosoftTeamsMessagesPostResponses,
    BotMessagesApiMicrosoftTeamsMessagesPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    url: '/api/microsoft/teams/messages',
    ...options,
  });
