// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateProjectEndpointApiProjectsPostResponse,
  GetProjectEndpointApiProjectProjectIdGetResponse,
  GetSharedResourceApiPublicShareTokenGetResponse,
  GetWorkflowProgressEndpointApiProgressWorkflowWorkflowRunIdProgressGetResponse,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse,
  ListProjectFilesEndpointApiProjectProjectIdFilesGetResponse,
  ListProjectsEndpointApiProjectsGetResponse,
  UpdateProjectEndpointApiProjectProjectIdPatchResponse,
} from './types.gen';

const workflowRunDetailSchemaResponseTransformer = (data: any) => {
  data.run = workflowRunSchemaResponseTransformer(data.run);
  return data;
};

const workflowRunSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  return data;
};

export const getWorkflowStateApiWorkflowsWorkflowRunIdGetResponseTransformer = async (
  data: any,
): Promise<GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse> => {
  data = workflowRunDetailSchemaResponseTransformer(data);
  return data;
};

const projectListItemSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  if (data.workflow_runs) {
    data.workflow_runs = data.workflow_runs.map((item: any) => workflowRunSchemaResponseTransformer(item));
  }
  return data;
};

const projectSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  data.publication_date = new Date(data.publication_date);
  return data;
};

export const listProjectsEndpointApiProjectsGetResponseTransformer = async (
  data: any,
): Promise<ListProjectsEndpointApiProjectsGetResponse> => {
  data = data.map((item: any) => projectListItemSchemaResponseTransformer(item));
  return data;
};

const projectDetailedSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  if (data.workflow_runs) {
    data.workflow_runs = data.workflow_runs.map((item: any) => workflowRunDetailSchemaResponseTransformer(item));
  }
  return data;
};

export const createProjectEndpointApiProjectsPostResponseTransformer = async (
  data: any,
): Promise<CreateProjectEndpointApiProjectsPostResponse> => {
  data = projectDetailedSchemaResponseTransformer(data);
  return data;
};

export const getProjectEndpointApiProjectProjectIdGetResponseTransformer = async (
  data: any,
): Promise<GetProjectEndpointApiProjectProjectIdGetResponse> => {
  data = projectDetailedSchemaResponseTransformer(data);
  return data;
};

export const updateProjectEndpointApiProjectProjectIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateProjectEndpointApiProjectProjectIdPatchResponse> => {
  data = projectSchemaResponseTransformer(data);
  return data;
};

const fileSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const listProjectFilesEndpointApiProjectProjectIdFilesGetResponseTransformer = async (
  data: any,
): Promise<ListProjectFilesEndpointApiProjectProjectIdFilesGetResponse> => {
  data = data.map((item: any) => fileSchemaResponseTransformer(item));
  return data;
};

const workflowProgressSchemaResponseTransformer = (data: any) => {
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getWorkflowProgressEndpointApiProgressWorkflowWorkflowRunIdProgressGetResponseTransformer = async (
  data: any,
): Promise<GetWorkflowProgressEndpointApiProgressWorkflowWorkflowRunIdProgressGetResponse> => {
  data = data.map((item: any) => workflowProgressSchemaResponseTransformer(item));
  return data;
};

export const getSharedResourceApiPublicShareTokenGetResponseTransformer = async (
  data: any,
): Promise<GetSharedResourceApiPublicShareTokenGetResponse> => {
  data = projectDetailedSchemaResponseTransformer(data);
  return data;
};
