// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateProjectEndpointApiProjectsPostResponse,
  CreateThreadApiChatThreadsPostResponse,
  ExportAnnotationsApiAdminAnnotationsExportGetResponse,
  GenerateThreadTitleApiChatThreadsThreadIdTitlePostResponse,
  GetAdminFeedbacksApiAdminFeedbacksGetResponse,
  GetDashboardApiAdminDashboardGetResponse,
  GetIssueEndpointApiIssuesIssueIdGetResponse,
  GetProjectIssuesEndpointApiProjectProjectIdIssuesGetResponse,
  GetProjectOverviewEndpointApiProjectProjectIdOverviewGetResponse,
  GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponse,
  GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponse,
  GetSharedResourceApiPublicShareTokenGetResponse,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse,
  ListAnnotatedItemsApiAdminAnnotationsSetsSlugItemsGetResponse,
  ListAppConfigsApiAppConfigsGetResponse,
  ListLogsApiAdminLogsGetResponse,
  ListProjectFilesEndpointApiProjectProjectIdFilesGetResponse,
  ListProjectsEndpointApiProjectsGetResponse,
  ListReviewAssistantRunsEndpointApiReviewAssistantProjectsProjectIdRunsGetResponse,
  ListRevisionsEndpointApiProjectProjectIdRevisionsGetResponse,
  ListThreadsApiChatThreadsGetResponse,
  ResolveIssueEndpointApiIssuesIssueIdResolvePostResponse,
  UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostResponse,
  UpdateAppConfigApiAppConfigsKeyPutResponse,
  UpdateProjectEndpointApiProjectProjectIdPatchResponse,
  UpdateThreadApiChatThreadsThreadIdPatchResponse,
} from './types.gen';

const activityPointSchemaResponseTransformer = (data: any) => {
  data.bucket = new Date(data.bucket);
  return data;
};

const activeUserItemSchemaResponseTransformer = (data: any) => {
  data.last_active_at = new Date(data.last_active_at);
  return data;
};

const adminDashboardResponseSchemaResponseTransformer = (data: any) => {
  data.period_start = new Date(data.period_start);
  data.period_end = new Date(data.period_end);
  data.activity = data.activity.map((item: any) => activityPointSchemaResponseTransformer(item));
  data.top_users = data.top_users.map((item: any) => activeUserItemSchemaResponseTransformer(item));
  return data;
};

export const getDashboardApiAdminDashboardGetResponseTransformer = async (
  data: any,
): Promise<GetDashboardApiAdminDashboardGetResponse> => {
  data = adminDashboardResponseSchemaResponseTransformer(data);
  return data;
};

const annotationRecordSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

const annotatedItemSchemaResponseTransformer = (data: any) => {
  data.annotations = data.annotations.map((item: any) => annotationRecordSchemaResponseTransformer(item));
  return data;
};

const annotationSetExportSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => annotatedItemSchemaResponseTransformer(item));
  return data;
};

export const exportAnnotationsApiAdminAnnotationsExportGetResponseTransformer = async (
  data: any,
): Promise<ExportAnnotationsApiAdminAnnotationsExportGetResponse> => {
  data = data.map((item: any) => annotationSetExportSchemaResponseTransformer(item));
  return data;
};

export const listAnnotatedItemsApiAdminAnnotationsSetsSlugItemsGetResponseTransformer = async (
  data: any,
): Promise<ListAnnotatedItemsApiAdminAnnotationsSetsSlugItemsGetResponse> => {
  data = data.map((item: any) => annotatedItemSchemaResponseTransformer(item));
  return data;
};

const appConfigResponseSchemaResponseTransformer = (data: any) => {
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const listAppConfigsApiAppConfigsGetResponseTransformer = async (
  data: any,
): Promise<ListAppConfigsApiAppConfigsGetResponse> => {
  data = data.map((item: any) => appConfigResponseSchemaResponseTransformer(item));
  return data;
};

export const updateAppConfigApiAppConfigsKeyPutResponseTransformer = async (
  data: any,
): Promise<UpdateAppConfigApiAppConfigsKeyPutResponse> => {
  data = appConfigResponseSchemaResponseTransformer(data);
  return data;
};

const chatThreadResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  return data;
};

export const listThreadsApiChatThreadsGetResponseTransformer = async (
  data: any,
): Promise<ListThreadsApiChatThreadsGetResponse> => {
  data = data.map((item: any) => chatThreadResponseSchemaResponseTransformer(item));
  return data;
};

export const createThreadApiChatThreadsPostResponseTransformer = async (
  data: any,
): Promise<CreateThreadApiChatThreadsPostResponse> => {
  data = chatThreadResponseSchemaResponseTransformer(data);
  return data;
};

export const updateThreadApiChatThreadsThreadIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateThreadApiChatThreadsThreadIdPatchResponse> => {
  data = chatThreadResponseSchemaResponseTransformer(data);
  return data;
};

export const generateThreadTitleApiChatThreadsThreadIdTitlePostResponseTransformer = async (
  data: any,
): Promise<GenerateThreadTitleApiChatThreadsThreadIdTitlePostResponse> => {
  data = chatThreadResponseSchemaResponseTransformer(data);
  return data;
};

const workflowRunPublicSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  if (data.heartbeat_at) {
    data.heartbeat_at = new Date(data.heartbeat_at);
  }
  return data;
};

const workflowRunDetailSchemaResponseTransformer = (data: any) => {
  data.run = workflowRunPublicSchemaResponseTransformer(data.run);
  return data;
};

export const getWorkflowStateApiWorkflowsWorkflowRunIdGetResponseTransformer = async (
  data: any,
): Promise<GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse> => {
  data = workflowRunDetailSchemaResponseTransformer(data);
  return data;
};

const issueEditReadSchemaResponseTransformer = (data: any) => {
  if (data.reviewed_at) {
    data.reviewed_at = new Date(data.reviewed_at);
  }
  return data;
};

const issueSchemaResponseTransformer = (data: any) => {
  if (data.resolved_at) {
    data.resolved_at = new Date(data.resolved_at);
  }
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  data.edits = data.edits.map((item: any) => issueEditReadSchemaResponseTransformer(item));
  return data;
};

const adminFeedbackItemSchemaResponseTransformer = (data: any) => {
  data.issue = issueSchemaResponseTransformer(data.issue);
  return data;
};

export const getAdminFeedbacksApiAdminFeedbacksGetResponseTransformer = async (
  data: any,
): Promise<GetAdminFeedbacksApiAdminFeedbacksGetResponse> => {
  data = data.map((item: any) => adminFeedbackItemSchemaResponseTransformer(item));
  return data;
};

const logFileInfoSchemaResponseTransformer = (data: any) => {
  data.modified_at = new Date(data.modified_at);
  return data;
};

export const listLogsApiAdminLogsGetResponseTransformer = async (
  data: any,
): Promise<ListLogsApiAdminLogsGetResponse> => {
  data = data.map((item: any) => logFileInfoSchemaResponseTransformer(item));
  return data;
};

const issueResponseSchemaResponseTransformer = (data: any) => {
  data.edits = data.edits.map((item: any) => issueEditReadSchemaResponseTransformer(item));
  return data;
};

export const resolveIssueEndpointApiIssuesIssueIdResolvePostResponseTransformer = async (
  data: any,
): Promise<ResolveIssueEndpointApiIssuesIssueIdResolvePostResponse> => {
  data = issueResponseSchemaResponseTransformer(data);
  return data;
};

export const unresolveIssueEndpointApiIssuesIssueIdUnresolvePostResponseTransformer = async (
  data: any,
): Promise<UnresolveIssueEndpointApiIssuesIssueIdUnresolvePostResponse> => {
  data = issueResponseSchemaResponseTransformer(data);
  return data;
};

export const getIssueEndpointApiIssuesIssueIdGetResponseTransformer = async (
  data: any,
): Promise<GetIssueEndpointApiIssuesIssueIdGetResponse> => {
  data = issueResponseSchemaResponseTransformer(data);
  return data;
};

const projectSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  data.publication_date = new Date(data.publication_date);
  return data;
};

const workflowRunSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  if (data.heartbeat_at) {
    data.heartbeat_at = new Date(data.heartbeat_at);
  }
  return data;
};

const projectListItemSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  if (data.workflow_runs) {
    data.workflow_runs = data.workflow_runs.map((item: any) => workflowRunSchemaResponseTransformer(item));
  }
  return data;
};

const projectListPageSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => projectListItemSchemaResponseTransformer(item));
  return data;
};

export const listProjectsEndpointApiProjectsGetResponseTransformer = async (
  data: any,
): Promise<ListProjectsEndpointApiProjectsGetResponse> => {
  data = projectListPageSchemaResponseTransformer(data);
  return data;
};

const projectCreatedSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  return data;
};

export const createProjectEndpointApiProjectsPostResponseTransformer = async (
  data: any,
): Promise<CreateProjectEndpointApiProjectsPostResponse> => {
  data = projectCreatedSchemaResponseTransformer(data);
  return data;
};

export const updateProjectEndpointApiProjectProjectIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateProjectEndpointApiProjectProjectIdPatchResponse> => {
  data = projectSchemaResponseTransformer(data);
  return data;
};

const fileSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const listProjectFilesEndpointApiProjectProjectIdFilesGetResponseTransformer = async (
  data: any,
): Promise<ListProjectFilesEndpointApiProjectProjectIdFilesGetResponse> => {
  data = data.map((item: any) => fileSchemaResponseTransformer(item));
  return data;
};

const workflowProgressResponseSchemaResponseTransformer = (data: any) => {
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponseTransformer = async (
  data: any,
): Promise<GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponse> => {
  data = data.map((item: any) => workflowProgressResponseSchemaResponseTransformer(item));
  return data;
};

const revisionListItemSchemaResponseTransformer = (data: any) => {
  if (data.created_at) {
    data.created_at = new Date(data.created_at);
  }
  return data;
};

export const listRevisionsEndpointApiProjectProjectIdRevisionsGetResponseTransformer = async (
  data: any,
): Promise<ListRevisionsEndpointApiProjectProjectIdRevisionsGetResponse> => {
  data = data.map((item: any) => revisionListItemSchemaResponseTransformer(item));
  return data;
};

const workflowRunSummarySchemaResponseTransformer = (data: any) => {
  data.run = workflowRunPublicSchemaResponseTransformer(data.run);
  return data;
};

const fileListItemSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

const projectOverviewSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  if (data.workflow_runs) {
    data.workflow_runs = data.workflow_runs.map((item: any) => workflowRunSummarySchemaResponseTransformer(item));
  }
  if (data.files) {
    data.files = data.files.map((item: any) => fileListItemSchemaResponseTransformer(item));
  }
  return data;
};

export const getProjectOverviewEndpointApiProjectProjectIdOverviewGetResponseTransformer = async (
  data: any,
): Promise<GetProjectOverviewEndpointApiProjectProjectIdOverviewGetResponse> => {
  data = projectOverviewSchemaResponseTransformer(data);
  return data;
};

export const getProjectIssuesEndpointApiProjectProjectIdIssuesGetResponseTransformer = async (
  data: any,
): Promise<GetProjectIssuesEndpointApiProjectProjectIdIssuesGetResponse> => {
  data = data.map((item: any) => issueSchemaResponseTransformer(item));
  return data;
};

export const getProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponseTransformer = async (
  data: any,
): Promise<GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponse> => {
  data = data.map((item: any) => workflowRunSummarySchemaResponseTransformer(item));
  return data;
};

export const getSharedResourceApiPublicShareTokenGetResponseTransformer = async (
  data: any,
): Promise<GetSharedResourceApiPublicShareTokenGetResponse> => {
  data = projectOverviewSchemaResponseTransformer(data);
  return data;
};

const reviewAssistantRunSchemaResponseTransformer = (data: any) => {
  data.run = workflowRunPublicSchemaResponseTransformer(data.run);
  return data;
};

export const listReviewAssistantRunsEndpointApiReviewAssistantProjectsProjectIdRunsGetResponseTransformer = async (
  data: any,
): Promise<ListReviewAssistantRunsEndpointApiReviewAssistantProjectsProjectIdRunsGetResponse> => {
  data = data.map((item: any) => reviewAssistantRunSchemaResponseTransformer(item));
  return data;
};
