// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateProjectEndpointApiProjectsPostResponse,
  GetAdminFeedbacksApiAdminFeedbacksGetResponse,
  GetProjectEndpointApiProjectProjectIdGetResponse,
  GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponse,
  GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponse,
  GetSharedResourceApiPublicShareTokenGetResponse,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse,
  ListAppConfigsApiAppConfigsGetResponse,
  ListProjectFilesEndpointApiProjectProjectIdFilesGetResponse,
  ListProjectsEndpointApiProjectsGetResponse,
  UpdateAppConfigApiAppConfigsKeyPutResponse,
  UpdateProjectEndpointApiProjectProjectIdPatchResponse,
} from './types.gen';

const appConfigResponseSchemaResponseTransformer = (data: any) => {
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const listAppConfigsApiAppConfigsGetResponseTransformer = async (
  data: any,
): Promise<ListAppConfigsApiAppConfigsGetResponse> => {
  data = data.map((item: any) => appConfigResponseSchemaResponseTransformer(item));
  return data;
};

export const updateAppConfigApiAppConfigsKeyPutResponseTransformer = async (
  data: any,
): Promise<UpdateAppConfigApiAppConfigsKeyPutResponse> => {
  data = appConfigResponseSchemaResponseTransformer(data);
  return data;
};

const workflowRunDetailSchemaResponseTransformer = (data: any) => {
  data.run = workflowRunSchemaResponseTransformer(data.run);
  return data;
};

const workflowRunSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  return data;
};

export const getWorkflowStateApiWorkflowsWorkflowRunIdGetResponseTransformer = async (
  data: any,
): Promise<GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse> => {
  data = workflowRunDetailSchemaResponseTransformer(data);
  return data;
};

const adminFeedbackItemSchemaResponseTransformer = (data: any) => {
  data.issue = issueSchemaResponseTransformer(data.issue);
  return data;
};

const issueSchemaResponseTransformer = (data: any) => {
  if (data.resolved_at) {
    data.resolved_at = new Date(data.resolved_at);
  }
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getAdminFeedbacksApiAdminFeedbacksGetResponseTransformer = async (
  data: any,
): Promise<GetAdminFeedbacksApiAdminFeedbacksGetResponse> => {
  data = data.map((item: any) => adminFeedbackItemSchemaResponseTransformer(item));
  return data;
};

const projectListItemSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  if (data.workflow_runs) {
    data.workflow_runs = data.workflow_runs.map((item: any) => workflowRunSchemaResponseTransformer(item));
  }
  return data;
};

const projectSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  data.publication_date = new Date(data.publication_date);
  return data;
};

export const listProjectsEndpointApiProjectsGetResponseTransformer = async (
  data: any,
): Promise<ListProjectsEndpointApiProjectsGetResponse> => {
  data = data.map((item: any) => projectListItemSchemaResponseTransformer(item));
  return data;
};

const projectDetailedSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  if (data.workflow_runs) {
    data.workflow_runs = data.workflow_runs.map((item: any) => workflowRunDetailSchemaResponseTransformer(item));
  }
  if (data.issues) {
    data.issues = data.issues.map((item: any) => issueSchemaResponseTransformer(item));
  }
  if (data.files) {
    data.files = data.files.map((item: any) => fileListItemSchemaResponseTransformer(item));
  }
  return data;
};

const fileListItemSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const createProjectEndpointApiProjectsPostResponseTransformer = async (
  data: any,
): Promise<CreateProjectEndpointApiProjectsPostResponse> => {
  data = projectDetailedSchemaResponseTransformer(data);
  return data;
};

export const getProjectEndpointApiProjectProjectIdGetResponseTransformer = async (
  data: any,
): Promise<GetProjectEndpointApiProjectProjectIdGetResponse> => {
  data = projectDetailedSchemaResponseTransformer(data);
  return data;
};

export const updateProjectEndpointApiProjectProjectIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateProjectEndpointApiProjectProjectIdPatchResponse> => {
  data = projectSchemaResponseTransformer(data);
  return data;
};

const fileSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const listProjectFilesEndpointApiProjectProjectIdFilesGetResponseTransformer = async (
  data: any,
): Promise<ListProjectFilesEndpointApiProjectProjectIdFilesGetResponse> => {
  data = data.map((item: any) => fileSchemaResponseTransformer(item));
  return data;
};

const workflowProgressResponseSchemaResponseTransformer = (data: any) => {
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponseTransformer = async (
  data: any,
): Promise<GetProjectWorkflowProgressEndpointApiProjectProjectIdWorkflowProgressGetResponse> => {
  data = data.map((item: any) => workflowProgressResponseSchemaResponseTransformer(item));
  return data;
};

export const getProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponseTransformer = async (
  data: any,
): Promise<GetProjectWorkflowRunsByTypeEndpointApiProjectProjectIdWorkflowRunsGetResponse> => {
  data = data.map((item: any) => workflowRunDetailSchemaResponseTransformer(item));
  return data;
};

export const getSharedResourceApiPublicShareTokenGetResponseTransformer = async (
  data: any,
): Promise<GetSharedResourceApiPublicShareTokenGetResponse> => {
  data = projectDetailedSchemaResponseTransformer(data);
  return data;
};
