"""Manifest for reference extraction workflow."""

from typing import List, Type

from langgraph.graph import StateGraph

from lib.workflows.claim_substantiation.state import (
    ClaimSubstantiatorState,
)
from lib.workflows.document_processing.state import DocumentProcessingState
from lib.workflows.manifest import WorkflowManifest
from lib.workflows.base import DocumentIssue, WorkflowRunType
from lib.workflows.reference_extraction.graph import build_reference_extraction_graph
from lib.workflows.reference_extraction.state import (
    ReferenceExtractionConfig,
    ReferenceExtractionState,
)
from lib.workflows.types import WorkflowState
from lib.workflows.util import get_state_by_type_or_raise


class ReferenceExtractionManifest(
    WorkflowManifest[ReferenceExtractionState, ReferenceExtractionConfig]
):
    """Manifest for reference extraction workflow."""

    type = WorkflowRunType.REFERENCE_EXTRACTION
    name = "Reference Extraction"
    description = "Extract bibliographic references from document using section detection and windowed extraction"
    needs_web_search = False
    is_internal = True  # Runs as dependency, not user-triggered from workflow list
    can_be_triggered_by_user = True  # Can be used as standalone tool
    required_dependencies = [WorkflowRunType.DOCUMENT_PROCESSING]

    def get_state_type(self) -> Type[ReferenceExtractionState]:
        """Get the type of the workflow state."""
        return ReferenceExtractionState

    def get_config_type(self) -> Type[ReferenceExtractionConfig]:
        """Get the type of the workflow config."""
        return ReferenceExtractionConfig

    def build_graph(self) -> StateGraph:
        """Build and return the graph of the workflow."""
        return build_reference_extraction_graph()

    async def create_initial_state(
        self,
        config: ReferenceExtractionConfig,
        existing_states: List[WorkflowState],
    ) -> ReferenceExtractionState:
        """
        Create initial state from DOCUMENT_PROCESSING dependency.

        Gets file with markdown from DOCUMENT_PROCESSING workflow.
        """
        # Get document processing artifacts
        doc_processing_state: DocumentProcessingState = get_state_by_type_or_raise(
            WorkflowRunType.DOCUMENT_PROCESSING, existing_states
        )

        return ReferenceExtractionState(
            config=config,
            file=doc_processing_state.file,  # Already has markdown populated
            supporting_files=doc_processing_state.supporting_files,
            supporting_documents_summaries=doc_processing_state.supporting_documents_summaries,
        )

    def convert_state_to_issues(
        self,
        state: ReferenceExtractionState,
        claim_state: ClaimSubstantiatorState,
    ) -> List[DocumentIssue]:
        """Convert reference extraction state to issues."""
        # No issues generated by this workflow currently
        return []

